/*
 * TabbedQueryTester.java
 *
 * Created on June 26, 2009, 9:51 AM
 */
package xmorph.edu.usu.applet;

import xmorph.edu.usu.grammar.XMorphParseException;
import org.xml.sax.SAXParseException;

/**
 *
 * @author  Curtis Dyreson
 */
public class TabbedQueryTester extends javax.swing.JApplet {

    Morph morph;

    /** Initializes the applet TabbedQueryTester */
    public void init() {
        morph = new Morph();
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabSelected = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        parseButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        queryText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        queryButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        outputText = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataShapeText = new javax.swing.JTextArea();
        dataShapeLabel = new javax.swing.JLabel();
        queryShapeLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        queryShapeText = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        inputText.setColumns(20);
        inputText.setRows(5);
        jScrollPane1.setViewportView(inputText);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("XML input");

        parseButton.setText("Parse Input");
        parseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parseInput(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(parseButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parseButton)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabSelected.addTab("Input", jPanel2);

        queryText.setColumns(20);
        queryText.setRows(5);
        jScrollPane3.setViewportView(queryText);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Morph query");

        queryButton.setText("Submit Query");
        queryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQuery(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(queryButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queryButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabSelected.addTab("Query", jPanel1);

        outputText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        outputText.setColumns(20);
        outputText.setRows(5);
        jScrollPane5.setViewportView(outputText);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabSelected.addTab("Output", jPanel3);

        dataShapeText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        dataShapeText.setColumns(20);
        dataShapeText.setRows(5);
        jScrollPane2.setViewportView(dataShapeText);

        dataShapeLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        dataShapeLabel.setText("Data's shape");
        dataShapeLabel.setToolTipText("This is the text of the data");

        queryShapeLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        queryShapeLabel.setText("Query's shape");
        queryShapeLabel.setToolTipText("This is the shape of the query.");

        queryShapeText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        queryShapeText.setColumns(20);
        queryShapeText.setRows(5);
        jScrollPane4.setViewportView(queryShapeText);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataShapeLabel))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(queryShapeLabel)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataShapeLabel)
                    .addComponent(queryShapeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabSelected.addTab("Shapes", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        tabSelected.addTab("Analysis", jPanel4);
        tabSelected.addTab("Type Info", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabSelected, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabSelected, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        tabSelected.getAccessibleContext().setAccessibleName("Input");
    }// </editor-fold>//GEN-END:initComponents

private void submitQuery(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQuery
// TODO add your handling code here:
    try {
        outputText.setText(morph.execute(queryText.getText()));
        queryShapeText.setText(morph.queryShape.imageXML());
    } catch (XMorphParseException e) {
        outputText.setText("There is an error in the syntax of the Morph query.\n" + e.msg);
        queryShapeText.setText("Parse error in query, see Output box.");
    } catch (Exception e) {
        StackTraceElement st[] = e.getStackTrace();
        String s = e.toString();
        for (StackTraceElement se : st) {
            s += se.toString();
        }
        outputText.setText(s);
        queryShapeText.setText("Error in query, see Output box.");
    }
}//GEN-LAST:event_submitQuery

private void parseInput(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parseInput
// TODO add your handling code here:
    try {
        morph.parse(inputText.getText());
        dataShapeText.setText(morph.dataShape.imageXML());
        outputText.setText("XML parsed successfully.  Ready to query.");
    } catch (SAXParseException e) {
        String s = "XML Parse error at line " + e.getLineNumber() + " column " + e.getColumnNumber() + ":" + e.getMessage();
        outputText.setText(s);
        dataShapeText.setText("Error in parsing XML.");
    } catch (Exception e) {
        StackTraceElement st[] = e.getStackTrace();
        String s = e.toString();
        for (StackTraceElement se : st) {
            s += se.toString();
        }
        outputText.setText(s);
        dataShapeText.setText("Error in parsing XML.");
    }
}//GEN-LAST:event_parseInput
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataShapeLabel;
    private javax.swing.JTextArea dataShapeText;
    private javax.swing.JTextArea inputText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea outputText;
    private javax.swing.JButton parseButton;
    private javax.swing.JButton queryButton;
    private javax.swing.JLabel queryShapeLabel;
    private javax.swing.JTextArea queryShapeText;
    private javax.swing.JTextArea queryText;
    private javax.swing.JTabbedPane tabSelected;
    // End of variables declaration//GEN-END:variables
}
