package xmorph.edu.usu.algebra;

//import xmorph.edu.usu.reporting.TypeInformation;
import xmorph.edu.usu.graph.TypeId;
import xmorph.edu.usu.graph.Path;
import xmorph.edu.usu.reporting.*;
import xmorph.edu.usu.database.Database;
import xmorph.edu.usu.shape.ShapeNode;
import java.util.*;

/* 
 * TODO: Implement class
 * The OrderBy class implements an order by operator.
 * Ordering can be ascending or descending.
 * Ordering is by the specified shape.
 */
public class OrderBy extends Type {

    Map<TypeId, HashSet<TypeId>> parentMap;

    /* Constructor for an order by operation */
    public OrderBy(Operator c, Operator right) {
        child = c;
        this.right = right;
        parentMap = new HashMap();
    }

    @Override
    /* Order by orders the roots of the Shape forest.
     */
    public ShapeNode evaluate(Database db, ShapeNode dataShape) {
        ShapeNode shapeNode = child.evaluate(db, dataShape);
        ShapeNode groupNode = right.evaluate(db, dataShape);
        for (ShapeNode aNode : shapeNode.getChildren()) {
            if (parentMap.containsKey(aNode.getBaseTypeId())) {
                // Somehow set ordering in here.
                //aNode.setDynamicallyGrouped(groupNode);
                if (TypeInformation.captureTypeInformation) {
                    TypeInformation.appendLn(
                            "Ordering for type " + db.typesTable.get(aNode.getBaseTypeId()).image());
                }
            }
        }
        return shapeNode;
    }

    @Override
    /* Returns a list of the types generated by the operator.
     * The List could be empty if this Type has been restricted,
     * otherwise the list will contain at most one element (the
     * single Type for this operator). 
     */
    public HashSet<TypeId> typeOf(Database db) {
        HashSet<TypeId> parentTypes = child.typeOf(db);
        HashSet<TypeId> childTypes = right.typeOf(db);
        types = new HashSet();

        // Find the minimal distance between all pairs of types
        for (TypeId parentTypeId : parentTypes) {
            int minimalDistance = Integer.MAX_VALUE;
            Path parentPath = db.typesTable.get(parentTypeId);
            parentMap.put(parentTypeId, new HashSet());
            if (TypeInformation.captureTypeInformation) {
                TypeInformation.appendLn("Ordering: Checking order type " + parentPath.image());
            }
            for (TypeId childTypeId : childTypes) {
                Path childPath = db.typesTable.get(childTypeId);
                int dist = parentPath.distanceToLCA(db, childPath);
                if (TypeInformation.captureTypeInformation) {
                    TypeInformation.appendLn(
                            "Ordering: Type distance from " + parentPath.image() + " to " + childPath.image() + " is " + dist + ".");
                }
                if (dist < Integer.MAX_VALUE && dist <= minimalDistance) {
                    if (dist < minimalDistance) {
                        //System.out.println("resetting types ");
                        parentMap.put(parentTypeId, new HashSet());
                        minimalDistance = dist;
                    }
                    // We have a pair of nodes that are connected
                    if (!parentMap.containsKey(parentTypeId)) {
                        parentMap.put(parentTypeId, new HashSet());
                    }
                    //System.out.println("adding type id " + parentTypeId.getDLN().toString() + " " + childTypeId.getDLN().toString());
                    parentMap.get(parentTypeId).add(childTypeId);

                    // Add this type to the types only if we actually have a child
                    types.add(parentTypeId);
                }
            }
        }
        return types;
    }

    @Override
    public void restrictType(HashSet<TypeId> goodTypes) {
        HashSet<TypeId> childTypes = new HashSet();
        for (TypeId t : goodTypes) {
            // First do the children
            HashSet<TypeId> children = parentMap.get(t);
            childTypes.addAll(children);
            //parentMapCopy.put(t, children);
        }
        child.restrictType(goodTypes);
        right.restrictType(childTypes);
    }
}
