package xmorph.edu.usu.algebra;

import xmorph.edu.usu.graph.TypeId;
import xmorph.edu.usu.shape.ShapeNode;
import xmorph.edu.usu.database.Database;
import xmorph.edu.usu.reporting.ErrorInformation;
import java.util.*;

/* The Type operator generates nodes for a single 
 * Type in the data.
 */
public class Type extends Operator {

    String s = "";
    String newName = "";

    public Type() {
    }

    public Type(TypeId t) {
        types = new HashSet();
        types.add(t);
        s = t.toString();
        newName = s;
    }

    public Type(String s) {
        this.s = s;
        this.newName = s;
        types = null;
    }

    @Override
    /* Returns a list of the types generated by the operator.
     * The List could be empty if this Type has been restricted,
     * otherwise the list will contain at most one element (the
     * single Type for this operator). 
     */
    public HashSet<TypeId> typeOf(Database db) {
        if (types == null && s != null) {
            types = new HashSet();

            List<TypeId> typeList = db.abbreviatedTypesTable.get(s);
            if (typeList == null) {
                System.err.println("Error: no type for " + s + " in the data.");
                ErrorInformation.appendLn("Error: no type for " + s + " in the data.");
            }
            for (TypeId t : typeList) {
                /* NEED TO ADD A CHECK HERE TO ENSURE THAT ONLY 
                 * TYPES FOR THIS DATA ARE ADDED
                 */
                //if (db.typeIdInData(t)) {
                types.add(t);
            //}
            }
        //types.addAll(db.abbreviatedTypesTable.get(s));
        }
        //System.out.println("ab type " + s);
        if ((types == null) || (types.size() == 0)) {
            System.out.println("Type.java Warning: no such type: " + s + " manufacturing type.");
            ErrorInformation.appendLn("Warning: no such type: " + s + " manufacturing type.");
        //types = new Vector();
        //System.exit(-1);
        }
        return types;
    }

    @Override
    /* Restrict the types if needed
     */
    public void restrictType(HashSet<TypeId> types) {
        /*
        System.out.println("restrictaaa  types ");
        for (TypeId t : types) {
        System.out.println("restricted type is " + t.getDLN().toString() + " " + t.getName());
        }
         */
        this.types = types;
    }

    @Override
    /* Evaluate the Type generating a Shape with the type of this
     * node as the children of the new Shape.
     */
    public ShapeNode evaluate(Database db, ShapeNode dataShape) {
        // The Type should be a leaf, so no child should be present
        // The shape should not be modified.
        //System.out.println("Type.java evaluate " + dataShape.imageXML());
        if (child != null) {
            System.err.println("Type is not a leaf!");
            System.exit(-1);
        }

        ShapeNode shape = new ShapeNode();

        for (TypeId myTypeId : types) {
            //System.out.println("My type is " + myTypeId.getDLN().toString() + " " + myTypeId.getName());
            myTypeId.setName(newName);
            ShapeNode shapeNode = new ShapeNode(myTypeId, db.lcaTable.get(myTypeId));
            shape.add(shapeNode);
        }

        return shape;
    }

    @Override
    /* Translate these type to some other name.
     */
    public void translate(Dictionary d) {
        //System.out.println("ffffoo " + s + " " + d.getValue(s));
        // Fetch this name
        newName = s;
        // Set the old name to the dictionary name
        s = d.getValue(s);
    }
}

