code: Tuple.class Table.class Database.class Id.class IdSet.class IdList.class StringCol.class Dbm.class IdEnumeration.class IntegerCol.class

Dbm.class: Dbm.java
	javac Dbm.java

IdList.class: IdList.java
	javac IdList.java

Table.class: Table.java
	javac Table.java

IntegerCol.class: IntegerCol.java
	javac IntegerCol.java

StringCol.class: StringCol.java
	javac StringCol.java

IdSet.class: IdSet.java
	javac IdSet.java

IdEnumeration.class: IdEnumeration.java
	javac IdEnumeration.java

Id.class: Id.java
	javac Id.java

Tuple.class: Tuple.java
	javac Tuple.java

Database.class: Database.java
	javac Database.java

clean: 
	rm -f *.class
