/*
 * MorphQueryTesterApplet.java
 *
 * Created on June 23, 2009, 5:24 PM
 */
package xmorph.edu.usu.applet;

import xmorph.edu.usu.grammar.XMorphParseException;

/**
 *
 * @author  Curtis Dyreson
 */
public class MorphQueryTesterApplet extends javax.swing.JApplet {

    Morph morph;

    /** Initializes the applet MorphQueryTesterApplet */
    public void init() {
        try {
            morph = new Morph();
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    //dataShapeTree = new javax.swing.JTree(RunCanned.dataShape);
                    //queryShapeTree = new javax.swing.JTree(RunCanned.queryShape);
                    initComponents();
                //dataShapeTree = new javax.swing.JTree(new javax.swing.tree.DefaultMutableTreeNode("asdf"));
                //queryShapeTree = new javax.swing.JTree(new javax.swing.tree.DefaultMutableTreeNode("queryf"));

                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        queryLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        OutputLabel = new javax.swing.JLabel();
        dataShapeLabel = new javax.swing.JLabel();
        queryShapeLabel = new javax.swing.JLabel();
        dataShapeTextPanel = new javax.swing.JScrollPane();
        dataShapeText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        queryShapeText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        queryAnalysisText = new javax.swing.JTextArea();
        queryAnalysisLabel = new javax.swing.JLabel();
        inputPane = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryText = new javax.swing.JTextArea();

        setStub(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Submit Query");
        jButton1.setToolTipText("Press this button to submit the query.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQuery(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        outputBox.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        outputBox.setColumns(20);
        outputBox.setEditable(false);
        outputBox.setRows(5);
        outputBox.setToolTipText("Output of the query will arrive here.");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, outputBox, org.jdesktop.beansbinding.ObjectProperty.create(), outputBox, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(outputBox);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 300, 190));

        queryLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        queryLabel.setText("Morph query");
        getContentPane().add(queryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        inputLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        inputLabel.setText("XML input");
        getContentPane().add(inputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        OutputLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        OutputLabel.setText("Output of query");
        getContentPane().add(OutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        dataShapeLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        dataShapeLabel.setText("Shape of the data");
        getContentPane().add(dataShapeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        queryShapeLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        queryShapeLabel.setText("Shape produced by query");
        getContentPane().add(queryShapeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        dataShapeText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        dataShapeText.setColumns(15);
        dataShapeText.setEditable(false);
        dataShapeText.setRows(5);
        dataShapeText.setText("Shape of the data will appear here...");
        dataShapeText.setPreferredSize(new java.awt.Dimension(20, 20));
        dataShapeTextPanel.setViewportView(dataShapeText);

        getContentPane().add(dataShapeTextPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 310, 160));

        queryShapeText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        queryShapeText.setColumns(15);
        queryShapeText.setEditable(false);
        queryShapeText.setRows(5);
        queryShapeText.setText("Shape of the query will appear here...");
        jScrollPane4.setViewportView(queryShapeText);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 310, 160));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Morph Query Tester");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        queryAnalysisText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        queryAnalysisText.setColumns(20);
        queryAnalysisText.setRows(5);
        queryAnalysisText.setText("Query analysis will appear here...");
        jScrollPane5.setViewportView(queryAnalysisText);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 310, 190));

        queryAnalysisLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        queryAnalysisLabel.setText("Analysis of information loss");
        getContentPane().add(queryAnalysisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        inputText.setColumns(20);
        inputText.setRows(5);
        inputText.setText("Enter XML input here...");
        inputPane.setViewportView(inputText);

        getContentPane().add(inputPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 300, 160));

        queryText.setColumns(20);
        queryText.setRows(5);
        queryText.setText("Enter Morph query here...");
        jScrollPane1.setViewportView(queryText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 300, 160));

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

private void submitQuery(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQuery
// TODO add your handling code here:
    try {
        morph.parse(inputText.getText());
        outputBox.setText(morph.execute(queryText.getText()));
        dataShapeText.setText(morph.dataShape.imageXML());
        queryShapeText.setText(morph.queryShape.imageXML());
    } catch (XMorphParseException e) {
        outputBox.setText("There is an error in the syntax of the Morph query.\n" + e.msg);
        queryShapeText.setText("Parse error in query, see Output box.");
    } catch (Exception e) {
        outputBox.setText("There is an error in the Morph query.\n" + e.toString());
        queryShapeText.setText("Error in query, see Output box.");
    }
//dataShapeTree = new javax.swing.JTree(RunCanned.dataShape);
//queryShapeTree = new javax.swing.JTree(RunCanned.dataShape);

//javax.swing.tree.DefaultMutableTreeNode rootNode = RunCanned.dataShape;
//javax.swing.tree.DefaultTreeModel treeModel = new javax.swing.tree.DefaultTreeModel(rootNode);
//dataShapeTree.setModel(treeModel);
//dataShapeTree.setShowsRootHandles(true);


}//GEN-LAST:event_submitQuery
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JLabel dataShapeLabel;
    private javax.swing.JTextArea dataShapeText;
    private javax.swing.JScrollPane dataShapeTextPanel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JScrollPane inputPane;
    private javax.swing.JTextArea inputText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea outputBox;
    private javax.swing.JLabel queryAnalysisLabel;
    private javax.swing.JTextArea queryAnalysisText;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JLabel queryShapeLabel;
    private javax.swing.JTextArea queryShapeText;
    private javax.swing.JTextArea queryText;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
