/*
 * MorphQueryTesterApplet.java
 *
 * Created on June 23, 2009, 5:24 PM
 */
package xmorph.edu.usu.applet;

import xmorph.edu.usu.grammar.XMorphParseException;

/**
 *
 * @author  Curtis Dyreson
 */
public class MorphQueryApplet extends javax.swing.JApplet {

    Morph morph;

    @Override
    /** Initializes the applet MorphQueryTesterApplet */
    public void init() {


        try {
            morph = new Morph();
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    //dataShapeTree = new javax.swing.JTree(RunCanned.dataShape);
                    //queryShapeTree = new javax.swing.JTree(RunCanned.queryShape);
                    initComponents();
                //dataShapeTree = new javax.swing.JTree(new javax.swing.tree.DefaultMutableTreeNode("asdf"));
                //queryShapeTree = new javax.swing.JTree(new javax.swing.tree.DefaultMutableTreeNode("queryf"));

                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        inputPane = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();
        OutputLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        queryLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dataShapeLabel = new javax.swing.JLabel();
        queryShapeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryText = new javax.swing.JTextArea();
        dataShapeTextPanel = new javax.swing.JScrollPane();
        dataShapeText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        queryShapeText = new javax.swing.JTextArea();
        queryAnalysisLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inputLabel.setText("XML input");
        jPanel1.add(inputLabel);

        inputText.setColumns(20);
        inputText.setRows(5);
        inputText.setText("Enter XML input here...");
        inputPane.setViewportView(inputText);

        jPanel1.add(inputPane);

        OutputLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OutputLabel.setText("Output of query");
        jPanel1.add(OutputLabel);

        outputBox.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        outputBox.setColumns(20);
        outputBox.setEditable(false);
        outputBox.setRows(5);
        outputBox.setToolTipText("Output of the query will arrive here.");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, outputBox, org.jdesktop.beansbinding.ObjectProperty.create(), outputBox, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(outputBox);

        jPanel1.add(jScrollPane2);

        queryLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        queryLabel.setText("Morph query");
        jPanel1.add(queryLabel);

        jButton1.setText("Submit Query");
        jButton1.setToolTipText("Press this button to submit the query.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQuery(evt);
            }
        });
        jPanel1.add(jButton1);

        dataShapeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dataShapeLabel.setText("Data's shape");
        jPanel1.add(dataShapeLabel);

        queryShapeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        queryShapeLabel.setText("Query's shape");
        jPanel1.add(queryShapeLabel);

        queryText.setColumns(5);
        queryText.setRows(5);
        queryText.setText("Enter Morph query here...");
        jScrollPane1.setViewportView(queryText);

        jPanel1.add(jScrollPane1);

        dataShapeText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        dataShapeText.setColumns(5);
        dataShapeText.setEditable(false);
        dataShapeText.setRows(5);
        dataShapeTextPanel.setViewportView(dataShapeText);

        jPanel1.add(dataShapeTextPanel);

        queryShapeText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        queryShapeText.setColumns(5);
        queryShapeText.setEditable(false);
        queryShapeText.setRows(5);
        queryShapeText.setMinimumSize(new java.awt.Dimension(30, 22));
        queryShapeText.setPreferredSize(new java.awt.Dimension(30, 94));
        jScrollPane4.setViewportView(queryShapeText);

        jPanel1.add(jScrollPane4);

        queryAnalysisLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        queryAnalysisLabel.setText("Information loss");
        jPanel1.add(queryAnalysisLabel);

        jRadioButton1.setText("Strongly typed");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);

        jRadioButton2.setText("Weakly typed (narrowing only)");
        jPanel1.add(jRadioButton2);

        jRadioButton3.setText("Weakly typed (widening only)");
        jPanel1.add(jRadioButton3);

        jRadioButton5.setText("Type error (word in query not in vocabulary)");
        jPanel1.add(jRadioButton5);

        jRadioButton4.setText("Weakly typed");
        jPanel1.add(jRadioButton4);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 460));

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

private void submitQuery(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQuery
// TODO add your handling code here:
    try {
        morph.parse(inputText.getText());
        outputBox.setText(morph.execute(queryText.getText()));
        dataShapeText.setText(morph.dataShape.imageXML());
        queryShapeText.setText(morph.queryShape.imageXML());
    } catch (XMorphParseException e) {
        outputBox.setText("There is an error in the syntax of the Morph query.\n" + e.msg);
        queryShapeText.setText("Parse error in query, see Output box.");
    } catch (Exception e) {
        outputBox.setText("There is an error in the Morph query.\n" + e.toString());
        queryShapeText.setText("Error in query, see Output box.");
    }

}//GEN-LAST:event_submitQuery

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JLabel dataShapeLabel;
    private javax.swing.JTextArea dataShapeText;
    private javax.swing.JScrollPane dataShapeTextPanel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JScrollPane inputPane;
    private javax.swing.JTextArea inputText;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea outputBox;
    private javax.swing.JLabel queryAnalysisLabel;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JLabel queryShapeLabel;
    private javax.swing.JTextArea queryShapeText;
    private javax.swing.JTextArea queryText;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
