/*
 * FlatQueryTester.java
 *
 * Created on July 6, 2009, 9:09 AM
 */
package xmorph.edu.usu.applet;

import xmorph.edu.usu.grammar.XMorphParseException;
import org.xml.sax.SAXParseException;

/**
 *
 * @author  Curtis Dyreson
 */
public class OldCannedQueryTester extends javax.swing.JApplet {

    Morph morph;

    /** Initializes the applet OldCannedQueryTester */
    public void init() {
        morph = new Morph();
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    String data = "<bibliography>\n";
                    data += "  <book>\n";
                    data += "    <title>DB</title>\n";
                    data += "    <author><name>E.F. Codd</name></author>\n";
                    data += "    <price>46.95</price>\n";
                    data += "    <publisher>Addison Wesley</publisher>\n";
                    data += "  </book>\n";
                    data += "  <book>\n";
                    data += "    <title>Automata</title>\n";
                    data += "    <author><name>E.F. Codd</name></author>\n";
                    data += "    <price>9.95</price>\n";
                    data += "    <publisher>Academic Press</publisher>\n";
                    data += "  </book>\n";
                    data += "</bibliography>\n";
                    initComponents();
                    queryText.setText(getParameter("query"));
                    inputText.setText(data);
                    parseInput(null);
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        inputPane = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();
        queryLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        OutputLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        dataShapeLabel = new javax.swing.JLabel();
        queryShapeLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        queryAnalysisLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        parseButton = new javax.swing.JButton();
        dataShapeTextPanel = new javax.swing.JScrollPane();
        dataShapeText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        queryShapeText = new javax.swing.JTextArea();

        inputLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        inputLabel.setText("XML input");

        inputText.setColumns(20);
        inputText.setRows(5);
        inputText.setText("Enter XML input here...");
        inputPane.setViewportView(inputText);

        queryLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        queryLabel.setText("Morph query");

        queryText.setColumns(5);
        queryText.setRows(5);
        queryText.setText("Enter Morph query here...");
        jScrollPane1.setViewportView(queryText);

        jButton1.setText("Submit Query");
        jButton1.setToolTipText("Press this button to submit the query.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQuery(evt);
            }
        });

        OutputLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        OutputLabel.setText("Output");

        outputBox.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        outputBox.setColumns(20);
        outputBox.setEditable(false);
        outputBox.setLineWrap(true);
        outputBox.setRows(5);
        outputBox.setToolTipText("Output of the query will arrive here.");
        jScrollPane2.setViewportView(outputBox);

        dataShapeLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        dataShapeLabel.setText("Data's shape");

        queryShapeLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        queryShapeLabel.setText("Query's shape");

        queryAnalysisLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        queryAnalysisLabel.setText("Information loss");

        jRadioButton1.setText("Strongly typed");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Weakly typed (narrowing only)");

        jRadioButton3.setText("Weakly typed (widening only)");

        jRadioButton5.setText("Type error (word in query not in vocabulary)");

        jRadioButton4.setText("Weakly typed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(queryAnalysisLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addGap(39, 39, 39)
                                .addComponent(jRadioButton5)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(queryAnalysisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap())
        );

        parseButton.setText("Parse XML");
        parseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parseInput(evt);
            }
        });

        dataShapeText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        dataShapeText.setColumns(5);
        dataShapeText.setEditable(false);
        dataShapeText.setLineWrap(true);
        dataShapeText.setRows(5);
        dataShapeTextPanel.setViewportView(dataShapeText);

        queryShapeText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        queryShapeText.setColumns(5);
        queryShapeText.setEditable(false);
        queryShapeText.setLineWrap(true);
        queryShapeText.setRows(5);
        queryShapeText.setMinimumSize(new java.awt.Dimension(30, 22));
        queryShapeText.setPreferredSize(new java.awt.Dimension(30, 94));
        jScrollPane4.setViewportView(queryShapeText);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(queryLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton1))
                                        .addComponent(inputPane, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inputLabel)
                                .addGap(18, 18, 18)
                                .addComponent(parseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OutputLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataShapeLabel)
                                    .addComponent(dataShapeTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(queryShapeLabel)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(OutputLabel)
                    .addComponent(parseButton))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(inputPane, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queryLabel)
                    .addComponent(jButton1)
                    .addComponent(dataShapeLabel)
                    .addComponent(queryShapeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(dataShapeTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Query", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void submitQuery(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQuery
// TODO add your handling code here:
    try {
        outputBox.setText(morph.execute(queryText.getText()));
        queryShapeText.setText(morph.queryShape.imageXML());
    } catch (XMorphParseException e) {
        outputBox.setText("There is an error in the syntax of the Morph query.\n" + e.msg);
        queryShapeText.setText("Parse error in query, see Output box.");
    } catch (Exception e) {
        StackTraceElement st[] = e.getStackTrace();
        String s = e.toString();
        for (StackTraceElement se : st) {
            s += se.toString();
        }
        outputBox.setText(s);
        queryShapeText.setText("Error in query, see Output box.");
    }
}//GEN-LAST:event_submitQuery

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButton1ActionPerformed

private void parseInput(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parseInput
// TODO add your handling code here:
    try {
        morph.parse(inputText.getText());
        dataShapeText.setText(morph.dataShape.imageXML());
        outputBox.setText("XML parsed successfully.  Ready to query.");
    } catch (SAXParseException e) {
        String s = "XML Parse error at line " + e.getLineNumber() + " column " + e.getColumnNumber() + ":" + e.getMessage();
        outputBox.setText(s);
        dataShapeText.setText("Error in parsing XML.");
    } catch (Exception e) {
        StackTraceElement st[] = e.getStackTrace();
        String s = e.toString();
        for (StackTraceElement se : st) {
            s += se.toString();
        }
        outputBox.setText(s);
        dataShapeText.setText("Error in parsing XML.");
    }
}//GEN-LAST:event_parseInput
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JLabel dataShapeLabel;
    private javax.swing.JTextArea dataShapeText;
    private javax.swing.JScrollPane dataShapeTextPanel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JScrollPane inputPane;
    private javax.swing.JTextArea inputText;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea outputBox;
    private javax.swing.JButton parseButton;
    private javax.swing.JLabel queryAnalysisLabel;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JLabel queryShapeLabel;
    private javax.swing.JTextArea queryShapeText;
    private javax.swing.JTextArea queryText;
    // End of variables declaration//GEN-END:variables
}
