code: CubetteSpecification.class LogRecord.class Cubette.class Federation.class

Federation.class: Federation.java
	javac Federation.java

LogRecord.class: LogRecord.java
	javac LogRecord.java

Cubette.class: Cubette.java
	javac Cubette.java

CubetteSpecification.class: CubetteSpecification.java
	javac CubetteSpecification.java

clean: 
	rm -f *.class
