
//----------------------------------------------------
// The following code was generated by CUP v0.9e
// Thu Jul 30 19:02:39 GMT+03:30 1998
//----------------------------------------------------

import java.io.*;
import java.util.*;
import java_cup.runtime.*;
import cube.globals.*;
import cube.database.*;
import cube.tools.*;
import cube.persistent.*;

public class parser extends java_cup.runtime.lr_parser {

  /** constructor */
  public parser() {super();}

  /** production table */
  protected static final short _production_table[][] = {
        {1, 3},     {0, 2},     {9, 2},     {9, 0},     {8, 2}, 
        {12, 0},     {7, 5},     {7, 0},     {2, 2},     {2, 0}, 
        {13, 0},     {3, 4},     {4, 3},     {4, 0},     {5, 2}, 
        {6, 2},     {14, 0},     {6, 2},     {11, 2},     {11, 0}, 
        {15, 0},     {10, 4}  };

  /** access to production table */
  public short[][] production_table() {return _production_table;}

  /** parse action table */
  protected static final short[][] _action_table = {
    /*0*/{4,3,6,-10,7,-10,-1,0},
    /*1*/{6,-4,7,26,-1,0},
    /*2*/{9,8,-1,0},
    /*3*/{0,7,-1,0},
    /*4*/{4,3,6,-10,7,-10,-1,0},
    /*5*/{6,-9,7,-9,-1,0},
    /*6*/{0,-2,-1,0},
    /*7*/{4,-11,5,-11,6,-11,7,-11,-1,0},
    /*8*/{4,-14,5,11,6,-14,7,-14,-1,0},
    /*9*/{4,-12,6,-12,7,-12,-1,0},
    /*10*/{9,25,-1,0},
    /*11*/{3,15,4,-17,5,-17,6,-17,7,-17,9,-17,-1,0},
    /*12*/{4,-20,5,-20,6,-20,7,-20,9,19,-1,0},
    /*13*/{4,-14,5,11,6,-14,7,-14,-1,0},
    /*14*/{10,16,-1,0},
    /*15*/{4,-16,5,-16,6,-16,7,-16,-1,0},
    /*16*/{4,-13,6,-13,7,-13,-1,0},
    /*17*/{4,-18,5,-18,6,-18,7,-18,-1,0},
    /*18*/{2,-21,-1,0},
    /*19*/{4,-20,5,-20,6,-20,7,-20,9,19,-1,0},
    /*20*/{4,-19,5,-19,6,-19,7,-19,-1,0},
    /*21*/{2,23,-1,0},
    /*22*/{9,24,-1,0},
    /*23*/{4,-22,5,-22,6,-22,7,-22,9,-22,-1,0},
    /*24*/{3,-15,4,-15,5,-15,6,-15,7,-15,9,-15,-1,0},
    /*25*/{6,-8,7,-8,9,31,-1,0},
    /*26*/{6,-4,7,26,-1,0},
    /*27*/{6,29,-1,0},
    /*28*/{0,-1,-1,0},
    /*29*/{6,-3,-1,0},
    /*30*/{8,33,-1,0},
    /*31*/{6,-5,7,-5,-1,0},
    /*32*/{9,34,-1,0},
    /*33*/{6,-6,7,-6,9,-6,-1,0},
    /*34*/{6,-8,7,-8,9,31,-1,0},
    /*35*/{6,-7,7,-7,-1,0},
  };

  /** access to parse action table */
  public short[][] action_table() {return _action_table;}

  /** reduce_goto table */
  protected static final short[][] _reduce_table = {
    /*0*/{1,3,2,1,3,4,-1,-1},
    /*1*/{8,26,9,27,-1,-1},
    /*2*/{-1,-1},
    /*3*/{-1,-1},
    /*4*/{2,5,3,4,-1,-1},
    /*5*/{-1,-1},
    /*6*/{-1,-1},
    /*7*/{13,8,-1,-1},
    /*8*/{4,9,5,11,-1,-1},
    /*9*/{-1,-1},
    /*10*/{-1,-1},
    /*11*/{6,13,14,12,-1,-1},
    /*12*/{10,19,11,17,-1,-1},
    /*13*/{4,16,5,11,-1,-1},
    /*14*/{-1,-1},
    /*15*/{-1,-1},
    /*16*/{-1,-1},
    /*17*/{-1,-1},
    /*18*/{15,21,-1,-1},
    /*19*/{10,19,11,20,-1,-1},
    /*20*/{-1,-1},
    /*21*/{-1,-1},
    /*22*/{-1,-1},
    /*23*/{-1,-1},
    /*24*/{-1,-1},
    /*25*/{7,31,-1,-1},
    /*26*/{8,26,9,29,-1,-1},
    /*27*/{-1,-1},
    /*28*/{-1,-1},
    /*29*/{-1,-1},
    /*30*/{-1,-1},
    /*31*/{-1,-1},
    /*32*/{-1,-1},
    /*33*/{12,34,-1,-1},
    /*34*/{7,35,-1,-1},
    /*35*/{-1,-1},
  };

  /** access to reduce_goto table */
  public short[][] reduce_table() {return _reduce_table;}

  /** instance of action encapsulation class */
  protected CUP$actions action_obj;

  /** action encapsulation object initializer */
  protected void init_actions()
    {
      action_obj = new CUP$actions();
    }

  /** invoke a user supplied parse action */
  public java_cup.runtime.symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$do_action(act_num, parser, stack, top);
  }

  /** start state */
  public int start_state() {return 0;}
  /** start production */
  public int start_production() {return 1;}

  /** EOF symbol index */
  public int EOF_sym() {return 0;}

  /** error symbol index */
  public int error_sym() {return 1;}


  /** user initialization */
  public void user_init() throws java.lang.Exception
    {
 
  lexer.init(Main.fileName); 
  
    }

  /** scan to get the next token */
  public java_cup.runtime.token scan()
    throws java.lang.Exception
    {
 return lexer.next_token(); 
    }
};

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$actions {


  protected CupFileWriter cupFile = Main.cupFile;
  protected LexFileWriter lexFile = Main.lexFile;
  protected String unitName = "";
  protected String measureName = "";
  protected IdSet measureSet = new IdSet();
  protected IdSet subunitSet = new IdSet();
  public int dimension = Main.whichDimension;


  /** Constructor */
  CUP$actions() { }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.symbol CUP$do_action(
    int                        CUP$act_num,
    java_cup.runtime.lr_parser CUP$parser,
    java.util.Stack            CUP$stack,
    int                        CUP$top)
    throws java.lang.Exception
    {
      /* object for return from actions */
      java_cup.runtime.symbol CUP$result;

      /* select the action based on the action number */
      switch (CUP$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // subunit ::= IDENTIFIER NT$3 PERIOD IDENTIFIER 
            {
              CUP$result = new symbol(/*subunit*/10);
               
    subunitSet.insert(Convert.toId((/*subunitunit*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val));
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // NT$3 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$3*/15);
               
    measureSet.insert(Convert.toId((/*subunitmeasure*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val));
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // subunits ::= 
            {
              CUP$result = new symbol(/*subunits*/11);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // subunits ::= subunit subunits 
            {
              CUP$result = new symbol(/*subunits*/11);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // unit ::= NT$2 subunits 
            {
              CUP$result = new symbol(/*unit*/6);
              
    cupFile.unitToSubunits(unitName, 
                           subunitSet, 
                           Main.global.finerUnitGraphs[dimension]);
    Id unitId = Convert.toId(unitName);
    for (Enumeration e = subunitSet.enumerate(); e.hasMoreElements();) {
      Id i = (Id)e.nextElement();
      Main.global.coarserUnitGraphs[dimension].addEdge(i,unitId);
      }
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NT$2 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$2*/14);
              
    cupFile.unitToMeasure(unitName, 
                          measureName, 
                          Main.global.unitToMeasureTables[dimension]);
    subunitSet = new IdSet();
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // unit ::= EQUALS REGULAR_EXPRESSION 
            {
              CUP$result = new symbol(/*unit*/6);
              
    cupFile.unitToMeasure(unitName, 
                          measureName, 
                          Main.global.unitToMeasureTables[dimension]);
    lexFile.emitTokenRule((/*regex*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val, unitName);
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // unitstart ::= UNIT IDENTIFIER 
            {
              CUP$result = new symbol(/*unitstart*/5);
              
    unitName = (/*unit*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val;
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // units ::= 
            {
              CUP$result = new symbol(/*units*/4);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // units ::= unitstart unit units 
            {
              CUP$result = new symbol(/*units*/4);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // measure ::= MEASURE IDENTIFIER NT$1 units 
            {
              CUP$result = new symbol(/*measure*/3);
              
    Id id = Convert.toId(measureName);
    for (Enumeration e = measureSet.enumerate(); e.hasMoreElements(); ) {
      Id i = (Id)e.nextElement();
      Main.global.coarserMeasureGraphs[dimension].addEdge(i, id);
      Main.global.finerMeasureGraphs[dimension].addEdge(id, i);
      }
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // NT$1 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$1*/13);
               
    measureName = (/*mezzz*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val;
    Id id = Convert.toId(measureName);
    Tuple t1 = new Tuple(id, id);
    Main.global.measureTables[dimension].insertTuple(t1);
    measureSet = new IdSet();
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // measures ::= 
            {
              CUP$result = new symbol(/*measures*/2);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // measures ::= measure measures 
            {
              CUP$result = new symbol(/*measures*/2);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // unit_list ::= 
            {
              CUP$result = new symbol(/*unit_list*/7);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // unit_list ::= IDENTIFIER AT IDENTIFIER NT$0 unit_list 
            {
              CUP$result = new symbol(/*unit_list*/7);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$0 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$0*/12);
              
    cupFile.addFilter((/*unit*/(str_token)CUP$stack.elementAt(CUP$top-2)).str_val, (/*measure*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val);
  
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // filter ::= FILTERS unit_list 
            {
              CUP$result = new symbol(/*filter*/8);
              
    cupFile.filter(Main.global.filterTable, 
                   Main.global.filterUnitTable, 
                   Main.global.filterMeasureTable);
  
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // filters ::= 
            {
              CUP$result = new symbol(/*filters*/9);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // filters ::= filter filters 
            {
              CUP$result = new symbol(/*filters*/9);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= prog EOF 
            {
              CUP$result = new java_cup.runtime.token(/*$START*/0);
              
            }
          /* ACCEPT */
          CUP$parser.done_parsing();
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // prog ::= measures filters SEMICOLON 
            {
              CUP$result = new symbol(/*prog*/1);
              
            }
          return CUP$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
};

