
//----------------------------------------------------
// The following code was generated by CUP v0.9e
// Mon Mar 24 02:50:39 EST 1997
//----------------------------------------------------

import java.io.*;
import java.util.*;
import java_cup.runtime.*;
import cube.globals.*;
import cube.database.*;
import cube.tools.*;
import cube.persistent.*;

public class parser extends java_cup.runtime.lr_parser {

  /** constructor */
  public parser() {super();}

  /** production table */
  protected static final short _production_table[][] = {
        {12, 0},     {13, 0},     {1, 5},     {0, 2},     {9, 2}, 
        {9, 0},     {8, 2},     {14, 0},     {7, 5},     {7, 0}, 
        {2, 2},     {2, 0},     {15, 0},     {3, 4},     {4, 3}, 
        {4, 0},     {5, 2},     {6, 2},     {16, 0},     {6, 2}, 
        {11, 2},     {11, 0},     {17, 0},     {10, 4}  };

  /** access to production table */
  public short[][] production_table() {return _production_table;}

  /** parse action table */
  protected static final short[][] _action_table = {
    /*0*/{5,-1,7,-1,8,-1,-1,0},
    /*1*/{5,6,7,-12,8,-12,-1,0},
    /*2*/{0,4,-1,0},
    /*3*/{0,-4,-1,0},
    /*4*/{7,-6,8,27,-1,0},
    /*5*/{10,9,-1,0},
    /*6*/{5,6,7,-12,8,-12,-1,0},
    /*7*/{7,-11,8,-11,-1,0},
    /*8*/{5,-13,6,-13,7,-13,8,-13,-1,0},
    /*9*/{5,-16,6,12,7,-16,8,-16,-1,0},
    /*10*/{5,-14,7,-14,8,-14,-1,0},
    /*11*/{10,26,-1,0},
    /*12*/{3,16,5,-19,6,-19,7,-19,8,-19,10,-19,-1,0},
    /*13*/{5,-22,6,-22,7,-22,8,-22,10,20,-1,0},
    /*14*/{5,-16,6,12,7,-16,8,-16,-1,0},
    /*15*/{11,17,-1,0},
    /*16*/{5,-18,6,-18,7,-18,8,-18,-1,0},
    /*17*/{5,-15,7,-15,8,-15,-1,0},
    /*18*/{5,-20,6,-20,7,-20,8,-20,-1,0},
    /*19*/{2,-23,-1,0},
    /*20*/{5,-22,6,-22,7,-22,8,-22,10,20,-1,0},
    /*21*/{5,-21,6,-21,7,-21,8,-21,-1,0},
    /*22*/{2,24,-1,0},
    /*23*/{10,25,-1,0},
    /*24*/{5,-24,6,-24,7,-24,8,-24,10,-24,-1,0},
    /*25*/{3,-17,5,-17,6,-17,7,-17,8,-17,10,-17,-1,0},
    /*26*/{7,-10,8,-10,10,33,-1,0},
    /*27*/{7,-6,8,27,-1,0},
    /*28*/{7,-2,-1,0},
    /*29*/{7,31,-1,0},
    /*30*/{0,-3,-1,0},
    /*31*/{7,-5,-1,0},
    /*32*/{9,35,-1,0},
    /*33*/{7,-7,8,-7,-1,0},
    /*34*/{10,36,-1,0},
    /*35*/{7,-8,8,-8,10,-8,-1,0},
    /*36*/{7,-10,8,-10,10,33,-1,0},
    /*37*/{7,-9,8,-9,-1,0},
  };

  /** access to parse action table */
  public short[][] action_table() {return _action_table;}

  /** reduce_goto table */
  protected static final short[][] _reduce_table = {
    /*0*/{1,2,12,1,-1,-1},
    /*1*/{2,4,3,6,-1,-1},
    /*2*/{-1,-1},
    /*3*/{-1,-1},
    /*4*/{8,27,9,28,-1,-1},
    /*5*/{-1,-1},
    /*6*/{2,7,3,6,-1,-1},
    /*7*/{-1,-1},
    /*8*/{15,9,-1,-1},
    /*9*/{4,10,5,12,-1,-1},
    /*10*/{-1,-1},
    /*11*/{-1,-1},
    /*12*/{6,14,16,13,-1,-1},
    /*13*/{10,20,11,18,-1,-1},
    /*14*/{4,17,5,12,-1,-1},
    /*15*/{-1,-1},
    /*16*/{-1,-1},
    /*17*/{-1,-1},
    /*18*/{-1,-1},
    /*19*/{17,22,-1,-1},
    /*20*/{10,20,11,21,-1,-1},
    /*21*/{-1,-1},
    /*22*/{-1,-1},
    /*23*/{-1,-1},
    /*24*/{-1,-1},
    /*25*/{-1,-1},
    /*26*/{7,33,-1,-1},
    /*27*/{8,27,9,31,-1,-1},
    /*28*/{13,29,-1,-1},
    /*29*/{-1,-1},
    /*30*/{-1,-1},
    /*31*/{-1,-1},
    /*32*/{-1,-1},
    /*33*/{-1,-1},
    /*34*/{-1,-1},
    /*35*/{14,36,-1,-1},
    /*36*/{7,37,-1,-1},
    /*37*/{-1,-1},
  };

  /** access to reduce_goto table */
  public short[][] reduce_table() {return _reduce_table;}

  /** instance of action encapsulation class */
  protected CUP$actions action_obj;

  /** action encapsulation object initializer */
  protected void init_actions()
    {
      action_obj = new CUP$actions();
    }

  /** invoke a user supplied parse action */
  public java_cup.runtime.symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$do_action(act_num, parser, stack, top);
  }

  /** start state */
  public int start_state() {return 0;}
  /** start production */
  public int start_production() {return 3;}

  /** EOF symbol index */
  public int EOF_sym() {return 0;}

  /** error symbol index */
  public int error_sym() {return 1;}


  /** user initialization */
  public void user_init() throws java.lang.Exception
    {
 
  lexer.init(Main.fileName); 
  
    }

  /** scan to get the next token */
  public java_cup.runtime.token scan()
    throws java.lang.Exception
    {
 return lexer.next_token(); 
    }
};

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$actions {


  protected CupFileWriter cupFile = new CupFileWriter("/home/curtis/classes/cube/parser/parser.cup");
  protected LexFileWriter lexFile = Main.lexFile;
  //protected Globals global = new Globals();
  protected String unitName = "";
  protected String measureName = "";
  protected IdSet measureSet = new IdSet();
  protected IdSet subunitSet = new IdSet();
  public int dimension = Main.whichDimension;


  /** Constructor */
  CUP$actions() { }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.symbol CUP$do_action(
    int                        CUP$act_num,
    java_cup.runtime.lr_parser CUP$parser,
    java.util.Stack            CUP$stack,
    int                        CUP$top)
    throws java.lang.Exception
    {
      /* object for return from actions */
      java_cup.runtime.symbol CUP$result;

      /* select the action based on the action number */
      switch (CUP$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // subunit ::= IDENTIFIER NT$5 PERIOD IDENTIFIER 
            {
              CUP$result = new symbol(/*subunit*/10);
               
    System.out.println("a subunit " + (/*subunitunit*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val + (Convert.ToId((/*subunitunit*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val)).image());
    subunitSet.insert(Convert.ToId((/*subunitunit*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val));
    //measureSet.insert(Convert.ToId((/*subunitmeasure*/(str_token)CUP$stack.elementAt(CUP$top-3)).str_val));
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // NT$5 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$5*/17);
               
    System.out.println("a submeasure " + (/*subunitmeasure*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val + (Convert.ToId((/*subunitmeasure*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val)).image());
    measureSet.insert(Convert.ToId((/*subunitmeasure*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val));
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // subunits ::= 
            {
              CUP$result = new symbol(/*subunits*/11);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // subunits ::= subunit subunits 
            {
              CUP$result = new symbol(/*subunits*/11);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // unit ::= NT$4 subunits 
            {
              CUP$result = new symbol(/*unit*/6);
              
    cupFile.unitToSubunits(unitName, subunitSet, Main.global.finerUnitGraphs[dimension]);
    Id unitId = Convert.ToId(unitName);
    for (Enumeration e = subunitSet.enumerate(); e.hasMoreElements();) {
      Id i = (Id)e.nextElement();
      System.out.println("Adding edge " + i.image());
      Main.global.coarserUnitGraphs[dimension].addEdge(i,unitId);
      }
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // NT$4 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$4*/16);
              
    //cupFile.nonterminal(unitName);
    cupFile.unitToMeasure(unitName, measureName, Main.global.unitToMeasureTables[dimension]);
    subunitSet = new IdSet();
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // unit ::= EQUALS REGULAR_EXPRESSION 
            {
              CUP$result = new symbol(/*unit*/6);
              
    cupFile.unitToMeasure(unitName, measureName, Main.global.unitToMeasureTables[dimension]);
    cupFile.terminal(unitName);
    lexFile.emitTokenRule((/*regex*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val, unitName);
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // unitstart ::= UNIT IDENTIFIER 
            {
              CUP$result = new symbol(/*unitstart*/5);
              
    unitName = (/*unit*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val;
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // units ::= 
            {
              CUP$result = new symbol(/*units*/4);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // units ::= unitstart unit units 
            {
              CUP$result = new symbol(/*units*/4);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // measure ::= MEASURE IDENTIFIER NT$3 units 
            {
              CUP$result = new symbol(/*measure*/3);
              
    for (Enumeration e = measureSet.enumerate(); e.hasMoreElements(); ) {
      Id i = (Id)e.nextElement();
      Main.global.coarserMeasureGraphs[dimension].addEdge(i, Convert.ToId(measureName));
      Main.global.finerMeasureGraphs[dimension].addEdge(Convert.ToId(measureName), i);
      }
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // NT$3 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$3*/15);
               
    measureName = (/*mezzz*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val;
    Id id = Convert.ToId(measureName);
    Tuple t = new Tuple(id, new Id(0));
    System.out.println("Adding tuple " + measureName + " " + t.getKeyAsString());
    Main.global.measureTables[dimension].insertTuple(t);
    measureSet = new IdSet();
    
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // measures ::= 
            {
              CUP$result = new symbol(/*measures*/2);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // measures ::= measure measures 
            {
              CUP$result = new symbol(/*measures*/2);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // unit_list ::= 
            {
              CUP$result = new symbol(/*unit_list*/7);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // unit_list ::= IDENTIFIER AT IDENTIFIER NT$2 unit_list 
            {
              CUP$result = new symbol(/*unit_list*/7);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NT$2 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$2*/14);
              
    cupFile.addFilter((/*unit*/(str_token)CUP$stack.elementAt(CUP$top-2)).str_val, (/*measure*/(str_token)CUP$stack.elementAt(CUP$top-0)).str_val);
  
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // filter ::= FILTERS unit_list 
            {
              CUP$result = new symbol(/*filter*/8);
              
    cupFile.filter(Main.global.filterTable, Main.global.filterUnitTable, Main.global.filterMeasureTable);
  
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // filters ::= 
            {
              CUP$result = new symbol(/*filters*/9);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // filters ::= filter filters 
            {
              CUP$result = new symbol(/*filters*/9);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // $START ::= prog EOF 
            {
              CUP$result = new java_cup.runtime.token(/*$START*/0);
              
            }
          /* ACCEPT */
          CUP$parser.done_parsing();
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // prog ::= NT$0 measures filters NT$1 SEMICOLON 
            {
              CUP$result = new symbol(/*prog*/1);
              
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$1 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$1*/13);
              
    cupFile.tail(Main.global.coarserUnitGraphs[dimension]);
    //lexFile.tail();
    //System.out.println("Filter Measure Table ");
    //System.out.println(Main.global.filterMeasureTable.IdKeysImage());
    //System.out.println(Main.global.filterMeasureTable.IdIdListImage());
    //System.out.println("Filter Unit Table ");
    //System.out.println(Main.global.filterUnitTable.IdKeysImage());
    //System.out.println(Main.global.filterUnitTable.IdIdListImage());
    //Main.global.coarserUnitGraphs[dimension].save();
    //Main.global.finerUnitGraphs[dimension].save();
    //Main.global.coarserMeasureGraphs[dimension].save();
    //Main.global.finerMeasureGraphs[dimension].save();
    //Main.global.filterTable.save();
    //Main.global.filterUnitTable.save();
    //Main.global.filterMeasureTable.save();
    //Main.global.unitToMeasureTables[dimension].save();

  
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // NT$0 ::= 
            {
              CUP$result = new java_cup.runtime.token(/*NT$0*/12);
              
    cupFile.header();
    //lexFile.header();
  
            }
          return CUP$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
};

