
//----------------------------------------------------
// The following code was generated by CUP v0.9e
// Thu Jul 30 19:02:39 GMT+03:30 1998
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int FILTERS = 7;
  static final int EOF = 0;
  static final int REGULAR_EXPRESSION = 10;
  static final int error = 1;
  static final int AT = 8;
  static final int IDENTIFIER = 9;
  static final int UNIT = 5;
  static final int PERIOD = 2;
  static final int SEMICOLON = 6;
  static final int EQUALS = 3;
  static final int MEASURE = 4;
};

