
//----------------------------------------------------
// The following code was generated by CUP v0.9e
// Tue Jan 14 01:14:03 EST 1997
//----------------------------------------------------

package java_cup.simple_calc;

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SEMI = 2;
  static final int EOF = 0;
  static final int DIVIDE = 6;
  static final int NUMBER = 10;
  static final int error = 1;
  static final int MINUS = 4;
  static final int TIMES = 5;
  static final int LPAREN = 8;
  static final int RPAREN = 9;
  static final int MOD = 7;
  static final int PLUS = 3;
};

