package xmorph.edu.usu.algebra;

//import xmorph.edu.usu.reporting.TypeInformation;
import xmorph.edu.usu.graph.TypeId;
import xmorph.edu.usu.graph.Path;
import xmorph.edu.usu.reporting.*;
import xmorph.edu.usu.database.Database;
import xmorph.edu.usu.shape.ShapeNode;
import java.util.*;

/* The Group class implements a static group operator.
 * Static groups are stored on disk with a group id.
 */
public class DynamicGroup extends Type {

    //HashSet<TypeId> groupTypes;
    //public Operator parent;
    Map<TypeId, HashSet<TypeId>> parentMap;

    /* Constructor for a dynamically grouped Type */
    public DynamicGroup(Operator c, Operator right) {
        //System.out.println("Child is " + c + " Right is " + right);
        child = c;
        this.right = right;
        parentMap = new HashMap();
    }

    @Override
    /* Group groups the roots of the Shape forest.
     */
    public ShapeNode evaluate(Database db, ShapeNode dataShape) {
        // The Type should be a leaf, so no child should be present
        ShapeNode shapeNode = child.evaluate(db, dataShape);
        ShapeNode groupNode = right.evaluate(db, dataShape);
        for (ShapeNode aNode : shapeNode.getChildren()) {
            //System.out.println("have parent ");
            if (parentMap.containsKey(aNode.getBaseTypeId())) {
                //System.out.println("shapes are " + aNode.imageXML() + "foo\n" + groupNode.imageXML() + "x");
                //for (ShapeNode c : shapeNode.getChildren()) {
                //    c.setDynamicallyGrouped(groupNode);
                //}
                aNode.setDynamicallyGrouped(groupNode);
                if (TypeInformation.captureTypeInformation) {
                    TypeInformation.appendLn(
                      "Dynamic grouping for type " + db.typesTable.get(aNode.getBaseTypeId()).image());
                }
            }
        }


        return shapeNode;
    }

    @Override
    /* Returns a list of the types generated by the operator.
     * The List could be empty if this Type has been restricted,
     * otherwise the list will contain at most one element (the
     * single Type for this operator). 
     */
    public HashSet<TypeId> typeOf(Database db) {
        // Initialize the types instance variable
        //types = child.typeOf(db);
        //groupTypes = right.typeOf(db);
        //return types;
        HashSet<TypeId> parentTypes = child.typeOf(db);
        HashSet<TypeId> childTypes = right.typeOf(db);
        types = new HashSet();

        // Find the minimal distance between all pairs of types
        for (TypeId parentTypeId : parentTypes) {
            int minimalDistance = Integer.MAX_VALUE;
            Path parentPath = db.typesTable.get(parentTypeId);
            parentMap.put(parentTypeId, new HashSet());
            if (TypeInformation.captureTypeInformation) {
                TypeInformation.appendLn("Dynamic Grouping: Checking group type " + parentPath.image());
            }
            for (TypeId childTypeId : childTypes) {
                Path childPath = db.typesTable.get(childTypeId);
                int dist = parentPath.distanceToLCA(db, childPath);
                //System.out.println(minimalDistance + " Distance is " + dist);
                if (TypeInformation.captureTypeInformation) {
                    TypeInformation.appendLn(
                      "Dynamic Grouping: Type distance from " + parentPath.image() + " to " + childPath.image() + " is " + dist + ".");
                }
                if (dist < Integer.MAX_VALUE && dist <= minimalDistance) {
                    if (dist < minimalDistance) {
                        //System.out.println("resetting types ");
                        parentMap.put(parentTypeId, new HashSet());
                        minimalDistance = dist;
                    }
                    // We have a pair of nodes that are connected
                    if (!parentMap.containsKey(parentTypeId)) {
                        parentMap.put(parentTypeId, new HashSet());
                    }
                    //System.out.println("adding type id " + parentTypeId.getDLN().toString() + " " + childTypeId.getDLN().toString());
                    parentMap.get(parentTypeId).add(childTypeId);

                    // Add this type to the types only if we actually have a child
                    types.add(parentTypeId);
                }
            }
        }
        return types;
    }

    @Override
    public void restrictType(
      HashSet<TypeId> goodTypes) {
        //child.restrictType(t);
        //right.restrictType(groupTypes);
        //System.out.println("Did we restrict type");
        //Map<TypeId, HashSet<TypeId>> parentMapCopy = new HashMap();
        HashSet<TypeId> childTypes = new HashSet();
        for (TypeId t : goodTypes) {
            // First do the children
            HashSet<TypeId> children = parentMap.get(t);
            childTypes.addAll(children);
        //parentMapCopy.put(t, children);
        }
        child.restrictType(goodTypes);
        right.restrictType(childTypes);
    }
}

