package xmorph.edu.usu.algebra;

import xmorph.edu.usu.graph.TypeId;
import xmorph.edu.usu.database.Database;
import xmorph.edu.usu.shape.ShapeNode;
import java.util.HashSet;

/* The Group class implements a static group operator.
 * Static groups are stored on disk with a group id.
 */
public class Group extends Type {

    /* Constructor for a dynamically grouped Type 
    public Group(Operator c) {
    }
    */

    /* Constructor for a grouped Type */
    public Group(Operator c) {
        child = c;
        //s = c.s;
        /* Curt commented out 
        types = AbbreviatedTypesCollection.get(s);

        //System.out.println("Group type " + s);
        if ((types == null) || (types.size() <= 0)) {
            System.out.println("Group.java Warning: no such type: " + s + " manufacturing type.");
            //types = new Vector();
            System.exit(-1);
        }
         */
    }

    @Override
    /* Group groups the roots of the Shape forest.
     */
    public ShapeNode evaluate(Database db, ShapeNode dataShape) {
        // The Type should be a leaf, so no child should be present
        ShapeNode shapeNode = child.evaluate(db, dataShape);
        for (ShapeNode c: shapeNode.getChildren()) {
            c.setGrouped();
        }
        return shapeNode;
    }

    @Override
    /* Returns a list of the types generated by the operator.
     * The List could be empty if this Type has been restricted,
     * otherwise the list will contain at most one element (the
     * single Type for this operator). 
     */
    public HashSet<TypeId> typeOf(Database db) {
        // Initialize the types instance variable
        types = child.typeOf(db);
        return types;
    }
}

