package xmorph.edu.usu.algebra;

import xmorph.edu.usu.graph.TypeId;
import xmorph.edu.usu.database.Database;
import xmorph.edu.usu.shape.ShapeNode;
import java.util.HashSet;

/* The Optional class implements an optional ShapeNode operator.
 */
public class Optional extends Type {

    /* Constructor for a Optional node in the Algebra. */
    public Optional(Operator c) {
        child = c;
    }

    @Override
    /* Optional should have a single child.
     */
    public ShapeNode evaluate(Database db, ShapeNode dataShape) {
        ShapeNode shapeNode = child.evaluate(db, dataShape);
        for (ShapeNode c: shapeNode.getChildren()) {
            c.setOptional();
        }
        return shapeNode;
    }

    @Override
    /* Returns a list of the types generated by the operator.
     * The List could be empty if this Type has been restricted,
     * otherwise the list will contain at most one element (the
     * single Type for this operator). 
     */
    public HashSet<TypeId> typeOf(Database db) {
        // Initialize the types instance variable
        types = child.typeOf(db);
        return types;
    }
}

