#!/usr/local/bin/perl -IC:\Inetpub\wwwroot\CDyreson\cgi-bin\perl\pm -IC:\Inetpub\wwwroot\CDyreson\cgi-bin\perl\quiz
 
# ****************************************************************
# regrader is a Perl program and CGI-bin script that regrades quiz
# questions as generated by QuizMaker.  For more info surf to
#       http://www.cs.jcu.edu.au/~curtis/software.html
# You are welcome to send bug reports, fixes, comments, questions or
# suggestions to Curtis Dyreson at curtis@cs.jcu.edu.au, but as I hope
# to have a real life someday I can't promise a swift reply.
#
# Copyright (c) 1996. All rights reserved.  This software is covered
# under the general license and lack of warranty as stated in the
# installation kit. WARNING! DANGER WILL ROBINSON! USE AT YOUR OWN RISK!
 
# persistent associative hash routines
use MyTextDB;
 
# Lincoln Stein's Fantabulous CGI package
use CGI;

$query = new CGI;
$ROOT = 'http://www.it.bond.edu.au/cdyreson/cgi-bin/perl/quiz';

# Build the header
print $query->header;

# Open databases
#$path = $query->param('path');
my ($junk, $rest) = split('/', $query->param('path'));
$path = "C:\\Inetpub\\wwwroot\\Cdyreson\\prweb\\quiz\\$rest";

&opendb(\%directionsdb, "$path\\directionsdb");
if (defined($directionsdb{'class'})) {
  $ROOT .= '/' . $directionsdb{'class'};
  }
&opendb(\%qdbm, "$path\\questiondb");

print $query->start_html('Marker','cdyreson@bond.edu.au');
# Make a security check
if (&entry_disallowed()) {
  print $query->end_html;
  exit();
  }

# Security passed, continue 
print $query->startform('POST',"$ROOT/stats.pl");
print &hidden('path',$query->param('path'));
print &hidden('password',$query->param('password'));
print &hidden('tute','allstats');
print $query->submit('entry', 'Return to Quiz Stats');
print $query->endform;

@question_list = split(",",$query->param('question_list'));
$question = (shift @question_list) || '';

#patch up answers to previous question!
if (!(defined($query->param('action_entry')) || defined($query->param('action_next')))) {
  &opendb(\%qanswerdb, "$path\\qanswer$question");
  &opendb(\%banswerdb, "$path\\banswer$question");
 
  @names = $query->param;
  @bresponses = ();
  @qresponses = ();
  foreach $name (@names) {
    if ($name =~ /bresponse/) { unshift @bresponses, $name; };
    if ($name =~ /qresponse/) { unshift @qresponses, $name; };
    }
  foreach $name (@qresponses) {
    if ($query->param($name) eq 'no') {
      $key = $query->param("h$name");
      $banswerdb{$key} = $qanswerdb{$key};
      delete $qanswerdb{$key};
      }
    }
  foreach $name (@bresponses) {
    if ($query->param("$name") eq 'yes') {
      $key = $query->param("h$name");
      $qanswerdb{$key} = $banswerdb{$key};
      delete $banswerdb{$key};
      }
    }
  foreach $name (@qresponses) {
    $query->delete("$name");
    $query->delete("h$name");
    }
  foreach $name (@bresponses) {
    $query->delete("$name");
    $query->delete("h$name");
    }
  &closedb(\%qanswerdb);
  &closedb(\%banswerdb);
  }

#do we skip on to the next question?
if ((defined($query->param('action_next'))) ||
    (defined($query->param('action_next_regrade')))) {
  $question = (shift @question_list) || '';
}

#if there are any more questions left...
if ($question) {
  &opendb(\%qanswerdb, "$path\\qanswer$question");
  &opendb(\%banswerdb, "$path\\banswer$question");
 
  $tute = $query->param('tute');
  &opendb(\%sdbm, "$path\\$tute");
 
  $total_answers = $sdbm{"$question-tried"};
  $a = "<BR> Correct student answers are (choose 'no' to make this response incorrect) \n <UL>";
  $s = "<BR> Incorrect student responses were (choose 'yes' to make this response correct)
\n <UL>";
  $i = 0;
  foreach $key (keys %qanswerdb) {
    if ($total_answers > 0)  {
      $percent = (10000 * $qanswerdb{$key} / $total_answers) % 10100;
      } 
    else {
      $percent = 0;
      }
    $percent = substr($percent,0,-2) . "." . substr($percent,-2,2);
    $a .= '<li>';
    $a .= $query->radio_group(-name=>"qresponse$i",
                                -values=>['yes', 'no'],
                                -default=>'yes');
    $s .= &hidden("hqresponse$i",$key);
 
    $a .= ' -- ';
    $a .= "$key -- $percent% (" . $qanswerdb{$key} . ")\n";
    $i += 1;
    }
  $i = 0;
  foreach $key (keys %banswerdb) {
    $percent = (10000 * $banswerdb{$key} / $total_answers) % 10100;
    $percent = substr($percent,0,-2) . "." . substr($percent,-2,2);
    $s .= '<li>';
    $s .= $query->radio_group(-name=>"bresponse$i",
                                -values=>['yes', 'no'],
                                -default=>'no');
    $s .= &hidden("hbresponse$i",$key);
 
    $s .= ' -- ';
    $s .= "$key -- $percent% (" . $banswerdb{$key} . ")\n";
    $i += 1;
    }
  &closedb(\%qanswerdb);
  &closedb(\%banswerdb);
  $s .= "</UL>\n";
  $a .= "</UL>\n";
  print '<HR>';
  print $query->startform('POST',"$ROOT/dummy.pl");
  print $qdbm{"$question"};
  print $query->endform;
  print $query->startform('POST',"$ROOT/regrader.pl");
  print &hidden('path',$query->param('path'));
  print &hidden('password',$query->param('password'));
  print &hidden('tute','allstats');
  print &hidden('question_list',join(",",($question,@question_list)));
  print $a;
  print $s;
  print $query->submit('action_next', 'Next');
  print $query->submit('action_next_regrade', 'Regrade and goto Next');
  print $query->submit('action_regrade', 'Regrade');
  print $query->endform;
  print '<HR>';
  }

print $query->end_html;

# Test the entry password, if it fails disallow entry to the
# survey and print an appropriate message
sub entry_disallowed {
  if ($query->param('password') eq $directionsdb{'stats-password'}) {return 0;}
  print "Sorry, stats are inactive.";
  return 1;
}

sub hidden {
  my ($name, $value) = @_;
  $query->param($name, $value);
  return $query->hidden($name, $value);
}
