#!/usr/local/bin/perl -IC:\Inetpub\wwwroot\CDyreson\cgi-bin\perl\pm -IC:\Inetpub\wwwroot\CDyreson\cgi-bin\perl\quiz
 
# ****************************************************************
# stats is a Perl program and CGI-bin script that marks quiz
# questions as generated by QuizMaker.  For more info surf to
#       http://www.cs.jcu.edu.au/~curtis/software.html
# You are welcome to send bug reports, fixes, comments, questions or
# suggestions to Curtis Dyreson at curtis@cs.jcu.edu.au, but as I hope
# to have a real life someday I can't promise a swift reply.
#
# Copyright (c) 1996. All rights reserved.  This software is covered
# under the general license and lack of warranty as stated in the
# installation kit. WARNING! DANGER WILL ROBINSON! USE AT YOUR OWN RISK!
 
# Persistent Hash
use MyTextDB;
# Lincoln Stein's Fantabulous CGI package
use CGI;
 
$query = new CGI;
$ROOT = 'http://www.it.bond.edu.au/cdyreson/cgi-bin/perl/quiz';

# Build the header
print $query->header;

# Open databases
my ($junk, $rest) = split('/', $query->param('path'));
$path = "C:\\Inetpub\\wwwroot\\Cdyreson\\prweb\\quiz\\$rest";
#$path = $query->param('path');

&openReadOnlydb(\%answerdb, "$path\\answerdb");
&openReadOnlydb(\%randomdb, "$path\\randomdb");
&openReadOnlydb(\%directionsdb, "$path\\directionsdb");
&openReadOnlydb(\%marksdb, "$path\\marksdb");
&openReadOnlydb(\%nmarksdb, "$path\\nmarksdb");
&opendb(\%smarksdb, "$path\\smarksdb");
if (defined $directionsdb{'class'}) {
  $ROOT .= '/' . $directionsdb{'class'};
  }
&openReadOnlydb(\%qdbm, "$path\\questiondb");

print $query->start_html('Marker','cdyreson@bond.edu.au');
print $directionsdb{'html-base'} . "\n";
# Make a security check
if (&entry_disallowed()) {
  print $query->end_html;
  exit();
  }

# Security passed, continue 

#print $query->dump;

if (defined($query->param('entry'))) { 
  # Create quiz answer database if not already created.
  foreach $key (keys %answerdb) {
    if (!(-e "$path\\qanswer$key.dir")) {
      &opendb(\%qanswerdb, "$path\\qanswer$key");
      @answer_list = split("\f",$answerdb{$key});
      shift @answer_list;
      foreach $answer (@answer_list) {
        $qanswerdb{$answer} = 0;
        }
      &closedb(\%qanswerdb);
      #&opendb(\%banswerdb, "$path\\banswer$key") 
      #&closedb(\%banswerdb);
      }
    }
  &create_stats();
  }
elsif (defined($query->param('action_email_to_students'))) { &mailmarks(); } 
elsif (defined($query->param('action_summary_email_to_instructor'))) { &mailsummarymarks(); } 
elsif (defined($query->param('action_email_to_instructor'))) { &mailmarks(); } 
elsif (defined($query->param('action_lookat'))) { &mailmarks(); } 

print $query->startform('POST',"$ROOT/regrader.pl");
print &hidden('path',$query->param('path'));
print &hidden('password',$query->param('password'));
print &hidden('tute','allstats');
print &hidden('question_list',join(",", &sortkeys(\%qdbm)));
print $query->submit('action_entry', 'Regrade Questions One-by-One');
print $query->endform;

print $query->startform('POST',"$ROOT/stats.pl");
print &hidden('path',$query->param('path'));
print &hidden('password',$query->param('password'));
print &hidden('tute','allstats');

print $query->submit("action_lookat", "Look at Results to Be Mailed");
print '<BR>';
print $query->submit("action_summary_email_to_instructor", "Mail Summary of Results to Instructor");
print '<BR>';
print 'Mail Results to ';
print $query->submit("action_email_to_instructor", "Instructor");
print $query->submit("action_email_to_students", "Students");
print "WARNING, choosing Students will send email to every student in class.";
print '<BR>';
print $query->endform;
print "Click on question number to regrade individual question.";

if (defined($query->param('tute'))) {
  print $query->startform('POST',"$ROOT/regrader.pl");
  print &hidden('path',$query->param('path'));
  print &hidden('password',$query->param('password'));
  print &hidden('tute','allstats');
  print &hidden('action_entry','entry');
  $query->delete('question_list');
  $tute = $query->param('tute');
  &openReadOnlydb(\%sdbm,"$path\\$tute");

  foreach $key (&sortkeys(\%qdbm)) {
    $tried = $sdbm{"$key-tried"};
    $correct = $sdbm{"$key-correct"};
    if ($tried) {
      $percent = (((100 * $correct) / $tried) % 101) . "%";
      $outof = "($correct out of $tried)";
      $button = $query->submit('question_list', "$key");
      }
    else {
      $pre = ''; 
      $percent = 'none tried';
      $outof = '';
      $button = $query->submit('question_list', "$key");
      }
    print "<BR> $pre $button $percent $outof \n";
    }
  print $query->endform;
}

print $query->end_html;

# Test the entry password, if it fails disallow entry to the
# survey and print an appropriate message
sub entry_disallowed {
  
  if ($query->param('password') eq $directionsdb{'stats-password'}) {return 0;}
  print "Sorry, stats are inactive.";
  return 1;
}

sub hidden {
  my ($name, $value) = @_;
  $query->param($name, $value);
  return $query->hidden($name, $value);
}
 
sub create_stats {
  &openAndCleardb(\%asdbm, "$path\\allstats");

  @keys = &sortkeys(\%qdbm);
  foreach $key (@keys) {
    $asdbm{"$key-tried"} = 0;
    $asdbm{"$key-correct"} = 0;
    $asdbm{"$key-answers"} = '';
    &opendb(\%qanswerdb, "$path\\qanswer$key");
    # reinitialize good answer db
    foreach $qkey (keys %qanswerdb) {
      $qanswerdb{$qkey} = 0;
      }
    &closedb(\%qanswerdb);
    # reinitialize bad answer db
    &opendb(\%banswerdb, "$path\\banswer$key");
    foreach $bkey (keys %banswerdb) {
      $banswerdb{$bkey} = 0;
      }
    &closedb(\%banswerdb);
    }

  # cycle through each student db in the directory
  opendir DIR, "$path"  || die "could not open directory $path: $!\n";
  my (@filenames) = grep { /^sadb/ && -f "$path\\$_" } readdir(DIR);
  closedir DIR;
  my $fileName;
  foreach $fileName (@filenames) {
    &openReadOnlydb(\%sanswerdb, "$path\\$fileName");
    $fileName =~ /^sadb\./;
    $userid = $';

    # cycle through each answer in the student db
    foreach $key (&sortkeys(\%sanswerdb)) {
      next if ($key eq "seed");
      next if ($key eq "total-right");
      next if ($key eq "total-tried");
      $answer = $sanswerdb{"$key"};
 
      &opendb(\%qanswerdb, "$path\\qanswer$key");
      &opendb(\%banswerdb, "$path\\banswer$key");

      $asdbm{"$key-tried"} = $asdbm{"$key-tried"} + 1;
      if (defined($qanswerdb{$answer})) { 
        $qanswerdb{$answer} += 1;
        $asdbm{"$key-correct"} = $asdbm{"$key-correct"} + 1;
        }
      elsif (defined($banswerdb{$answer})) { $banswerdb{$answer} += 1; }
      else { $banswerdb{$answer} = 1; }
    
      &closedb(\%qanswerdb);
      &closedb(\%banswerdb);
      }
    &closedb(\%sanswerdb);
    }
  &closedb(\%asdbm);
}

sub mailmarks {
  &opendb(\%asdbm, "$path\\allstats");

  # cycle through each student db in the directory
  opendir DIR, "$path"  || die "could not open directory $path: $!\n";
  my (@filenames) = grep { /^sadb/ && -f "$path\\$_" } readdir(DIR);
  closedir DIR;
  my $fileName;
  foreach $fileName (@filenames) {
    &openReadOnlydb(\%sanswerdb, "$path\\$fileName");
    $fileName =~ /^sadb\./;
    $userid = $';

    my @question_list = ();
    my @good_question_list = ();
    my $student_marks = 0;

    if (defined $sanswerdb{'seed'}) {
      $seed = $sanswerdb{'seed'};
      srand($seed);
      @keys = keys %randomdb;
      $questions_max = scalar(@keys);
      for ($i=1; $i <= $questions_max; $i++) {
        $j = int(rand($randomdb{$i})) + 1;
        $question = "$i:$j";
        push(@question_list,$question);
        }
      }
    else {
      # This is one-time to figure out the bad junk
      @good_question_list = ();
      @keys = keys %sanswerdb;
      $questions_max = scalar(@keys);
      @question_list = &sortkeys(\%sanswerdb);
      foreach $key (@question_list) {
        next unless $key;
        $student_answer = $sanswerdb{"$key"} || "no answer given";
        ($question, $variant) = split(":", $key);
        &openReadOnlydb(\%qanswerdb, "$path\\qanswer$key");
        if (defined $qanswerdb{$student_answer}) {
          $good_question_list[$question] = $key;
          }
        &closedb(\%qanswerdb);
        }
      foreach $key (@question_list) {
        ($question, $variant) = split(":", $key);
        $good_question_list[$question] = $key
           unless defined $good_question_list[$question];
        }
      @question_list = @good_question_list;
      shift @question_list;
      }
 
    # compute total marks
    my $total_marks = 0;
    foreach $key (@question_list) {
      $total_marks += $marksdb{$key};
      }
 
    $msg = "";
    # cycle through each question that the student replied to
    foreach $key (@question_list) {
      $student_answer = $sanswerdb{"$key"} || "no answer given";
      &openReadOnlydb(\%qanswerdb, "$path\\qanswer$key");

      if (defined($qanswerdb{$student_answer})) { 
        $student_marks += $marksdb{"$key"};
        }
      else {
        $student_marks -= $nmarksdb{"$key"};
        $correct = join("' or\n       `", keys %qanswerdb);
        my $student_answers = 'none given';
        $student_answers = join("' or `",split("\f",$sanswerdb{"$key"}));
        ($just_question_num) = split(":",$key);
        $ttt = $qdbm{"$key"};
        ($ttt) = split("<ADDRESS>",$ttt);
        $ttt =~ s/\n//;
        $ttt =~ s/\n//;
        $ttt =~ s/<tt>//ig;
        $ttt =~ s/a">\n/a>/g;
        $ttt =~ s/b">\n/b>/g;
        $ttt =~ s/c">\n/c>/g;
        $ttt =~ s/d">\n/d>/g;
        $ttt =~ s/e">\n/e>/g;
        $ttt =~ s/f">\n/f>/g;
        $ttt =~ s/Put your answer here.*//g;
        $ttt =~ s/INPUT TYPE="submit" NAME="answer" VALUE="//g;
        $ttt =~ s/INPUT TYPE="submit" NAME="ignore" VALUE="//g;
        $ttt =~ s/<INPUT TYPE="hidden" NAME="answer" VALUE="">//g;
        $ttt =~ s/<SELECT NAME="answer" SIZE=\d MULTIPLE>//ig;
        $ttt =~ s/<\/SELECT>//ig;
        $ttt =~ s/<OPTION>/\n OPTION /g;
        $ttt =~ s/<\/tt>//ig;
        $ttt =~ s/<BR>//ig;
        $ttt =~ s/<\/BODY>//ig;
        $ttt =~ s/<\/HTML>//ig;
        $ttt =~ s/<P>//ig;
        $ttt =~ s/<PRE>//ig;
        $ttt =~ s/<\/PRE>//ig;
        $ttt =~ s/<HR>//ig;
        $ttt =~ s/<H1>//ig;
        $ttt =~ s/<\/H1>//ig;
        $ttt =~ s/<Click Here When Done\>//g;
        $ttt =~ s/<true>//g;
        $ttt =~ s/<false>//g;
        $ttt =~ s/<a>/\n<a>/g;
        $msg .= "\n--------------------------------------------------------\n";
        $msg .= $ttt .
                  "   your answer was `$student_answers'\n" .
                  "   accepted answers are `$correct'\n" ;
        }
      &closedb(\%qanswerdb);
      }
    $smarksdb{$userid} = join(',', ($student_marks,$total_marks));
    &closedb(\%sanswerdb);

    $result = "*****This message is automatically generated*****\n" ;
    if (defined($query->param('action_email_to_students'))) {
      $result .= "You scored $student_marks out of $total_marks, or ";
      }
    else {
      $result .= "$userid scored $student_marks out of $total_marks, or ";
      }
    $result .= sprintf("%3.2f",($student_marks / $total_marks) * 100);
    $result .= "%.\n\n";
    if ($msg) { 
      $result .= "The questions that were marked as wrong are listed below.\n";
      $result .= $msg;
      }
    else {
      $result .= "Congratulations on your perfect mark.\n";
      }
   
    $result .= "\nHere is an overall statistical breakdown on the quiz.\n";
    $result .= "         | # that   | # that    | % who answered \n";
    $result .= "         | attempted| answered  | answered       \n";
    $result .= "question | question | correctly | correctly      \n";
    $result .= "------------------------------------------------ \n";
    foreach $question (@question_list) {
      ($just_question_num) = split(":",$question);
      $tried = $asdbm{"$question-tried"};
      $correct = $asdbm{"$question-correct"};
      if ($tried) { $percentage = ($correct / $tried) * 100.0;}
      else {$percentage = 0;}
      $result .= "    " . substr("  " . $just_question_num, -3,3) . "  |   " .
               substr("  " . $tried,-3,3) . "    |   " .
               substr("  " . $correct,-3,3) . "     |    " .
               substr("   " . int($percentage), -3, 3) . "\%\n";
      }
    $class = $directionsdb{'class'};

    # Remove any form feeds in the message
    $result =~ s/\f/ /g;
    if (defined($query->param('action_email_to_students'))) {
      # add instructor check
      die "no instructor email address" unless defined $directionsdb{'email'};
      $mailto = $directionsdb{'email'};
      # for fake quiz
      if (-e "$path\\passworddb") {
        open(MAIL,"|/usr/bin/mailx -s \"$class quiz results\" $userid\@jcu.edu.au $mailto") || die "cannot open mailx! contact god";
        print MAIL $result;
        close(MAIL);
        }
      }

    elsif (defined($query->param('action_email_to_instructor'))) {
      die "no instructor email address" unless defined $directionsdb{'email'};
      $mailto = $directionsdb{'email'};
      # for fake quiz
      if (-e "$path\\passworddb") {
        open(MAIL,"|/usr/bin/mailx -s \"$class quiz results\" $mailto") || die "cannot open mailx! contact god";
        print MAIL $result;
        close(MAIL);
        }
      }
    elsif (defined($query->param('action_lookat'))) {
      print '<PRE>';
      $result =~ s/\</&lt/g;
      $result =~ s/\>/&gt/g;
      print $result;
      print '</PRE>';
      }
    }
  &closedb(\%asdbm);
}

sub mailsummarymarks {
  &opendb(\%asdbm, "$path\\allstats");

  # cycle through each student db in the directory
  $result = " ";
  opendir DIR, "$path"  || die "could not open directory $path: $!\n";
  my (@filenames) = grep { /^sadb/ && -f "$path\\$_" } readdir(DIR);
  closedir DIR;
  # run through all the stats and collect them
  my $fileName;
  foreach $fileName (@filenames) {
    $fileName =~ /^sadb\./;
    $userid = $';
    my @question_list = ();
    my @good_question_list = ();

    &openReadOnlydb(\%sanswerdb, "$path\\$fileName");

    my $student_marks = 0;

    if (defined $sanswerdb{'seed'}) {
      $seed = $sanswerdb{'seed'};
      srand($seed);
      @keys = keys %randomdb;
      $questions_max = scalar(@keys);
      for ($i=1; $i <= $questions_max; $i++) {
        $j = int(rand($randomdb{$i})) + 1;
        $question = "$i:$j";
        push(@question_list,$question);
        }
      }
    else {
      # This is one-time to figure out the bad junk
      @good_question_list = ();
      @keys = keys %sanswerdb;
      $questions_max = scalar(@keys);
      @question_list = &sortkeys(\%sanswerdb);
      foreach $key (@question_list) {
        next unless $key;
        $student_answer = $sanswerdb{"$key"} || "no answer given";
        ($question, $variant) = split(":", $key);
        &openReadOnlydb(\%qanswerdb, "$path\\qanswer$key");
        if (defined $qanswerdb{$student_answer}) {
          $good_question_list[$question] = $key;
          }
        &closedb(\%qanswerdb);
        }
      foreach $key (@question_list) {
        ($question, $variant) = split(":", $key);
        $good_question_list[$question] = $key 
           unless defined $good_question_list[$question];
        }
      @question_list = @good_question_list;
      shift @question_list;
      }

    # compute total marks
    my $total_marks = 0;
    foreach $key (@question_list) {
      $total_marks += $marksdb{$key};
      }
 
    $msg = "";
    # cycle through each question that the student replied to
    foreach $key (@question_list) {
      $student_answer = $sanswerdb{"$key"} || "no answer given";
      &openReadOnlydb(\%qanswerdb, "$path\\qanswer$key");

      if (defined($qanswerdb{$student_answer})) { 
        $student_marks += $marksdb{"$key"};
        }
      &closedb(\%qanswerdb);
      }
    $result .= "$userid scored $student_marks out of $total_marks\n";
    $smarksdb{userid} = join(',', ($student_marks,$total_marks));
    &closedb(\%sanswerdb);
    }
  $class = $directionsdb{'class'};
  die "no instructor email address" unless defined($directionsdb{'email'});
  $mailto = $directionsdb{'email'};
  # for fake quiz
  if (-e "$path\\passworddb") {
    open(MAIL,"|/usr/bin/mailx -s \"$class quiz results\" $mailto") || die "cannot open mailx! contact god";
    print MAIL $result;
    close(MAIL);
    }
  &closedb(\%asdbm);
}

sub sortkeys {
  my ($hashref) = @_;
  my @questions = map { $_->[0] }
                  sort { $a->[1] <=> $b->[1]
                                  ||
                         $a->[2] <=> $b->[2]
                  } map { [$_, /(\d+):(\d+)/, uc($_)] } keys %$hashref;
  return @questions;
}  
 

