JAVA_FLAGS=-classpath ../..
#code: Globals.class Dimension.class
code: Globals.class 

Globals.class: Globals.java 
	javac $(JAVA_FLAGS) Globals.java

#Dimension.class: Dimension.java 
#	javac Dimension.java

clean: 
	rm -f *.class
