code: CubeGUI.class MessageLayout.class MessageHandler.class 

CubeGUI.class: CubeGUI.java
	javac CubeGUI.java

MessageLayout.class: MessageLayout.java
	javac MessageLayout.java

MessageHandler.class: MessageHandler.java
	javac MessageHandler.java

clean: 
	rm -f *.class
