all: CubetteSpecification.class LogRecord.class Cubette.class AnswerSet.class Main.class

Main.class: Main.java
	javac Main.java

AnswerSet.class: AnswerSet.java
	javac AnswerSet.java

LogRecord.class: LogRecord.java
	javac LogRecord.java

Cubette.class: Cubette.java
	javac Cubette.java

CubetteSpecification.class: CubetteSpecification.java
	javac CubetteSpecification.java

clean: 
	rm -f *.class
