#!/usr/bin/perl -I/home/cdyreson/public_html/cgi-bin/perl/pm
 
# ****************************************************************
# regrader is a Perl program and CGI-bin script that regrades quiz
# questions as generated by QuizMaker.  For more info surf to
#       http://www.cs.jcu.edu.au/~curtis/software.html
# You are welcome to send bug reports, fixes, comments, questions or
# suggestions to Curtis Dyreson at curtis@cs.jcu.edu.au, but as I hope
# to have a real life someday I can't promise a swift reply.
#
# Copyright (c) 1996. All rights reserved.  This software is covered
# under the general license and lack of warranty as stated in the
# installation kit. WARNING! DANGER WILL ROBINSON! USE AT YOUR OWN RISK!
 
# persistent associative hash routines
use MyTextDB;
 
# Lincoln Stein's Fantabulous CGI package
use CGI;

# HTML junk
use HTML::Entities;

$query = new CGI;
$ROOT = 'http://www.cs.usu.edu/cgi-bin/cgiwrap/~cdyreson/perl/QuizMaker';

# Build the header
print $query->header;

# Open databases
#$path = $query->param('path');
#my ($junk, $rest) = split('/', $query->param('path'));
#$path = "C:\\Inetpub\\wwwroot\\Cdyreson\\prweb\\quiz\\$rest";
my ($path) = $query->param('path');
$path = '/home/cdyreson/prweb/QuizMaker' . '/' . $path;

&openReadOnlydb(\%directionsdb, "$path/directionsdb");
if (defined($directionsdb{'class'})) {
  $ROOT .= '/' . $directionsdb{'class'};
  }
&openReadOnlydb(\%qdbm, "$path/questiondb");

print $query->start_html('Marker','cdyreson@eecs.wsu.edu.au');
print $directionsdb{'html-base'} . "\n";
# Make a security check
if (&entry_disallowed()) {
  print $query->end_html;
  exit();
  }

# Security passed, continue 
print $query->startform('POST',"$ROOT/stats.pl");
print &hidden('path',$query->param('path'));
print &hidden('password',$query->param('password'));
print &hidden('tute','allstats');
print $query->submit('entry', 'Return to Quiz Stats');
print $query->endform;

@question_list = split(",",$query->param('question_list'));
$question = (shift @question_list) || '';

#patch up answers to previous question!
if (!(defined($query->param('action_entry')) || defined($query->param('action_next')))) {
  &opendb(\%mqanswerdb, "$path/qanswer$question");
 
  my @names = $query->param;
  my @responses = ();
  foreach my $name (@names) {
    if ($name =~ /^response/) { unshift @responses, $name; };
    }
  foreach my $name (@responses) {
    if (defined $query->param($name)) {
      my $value = $query->param($name);
      my $key = $query->param("h$name");
      $mqanswerdb{$key} = $value;
      }
    }
  # taken care of below!!!!
  #foreach my $name (@responses) {
  #  $query->delete($name);
  #  $query->delete("h$name");
  #  }
  &closedb(\%mqanswerdb, "$path/qanswer$question");
  }

#do we skip on to the next question?
if ((defined($query->param('action_next'))) ||
    (defined($query->param('action_next_regrade')))) {
  $question = (shift @question_list) || '';
}

#if there are any more questions left...
my %qanswerdb = ();
my $a = '';
foreach my $key (keys %qanswerdb) { delete $qanswerdb{$key}; }
if ($question) {
  &opendb(\%qanswerdb, "$path/qanswer$question");
  &opendb(\%percentdb, "$path/percent$question");
 
  $tute = $query->param('tute');
  &openReadOnlydb(\%sdbm, "$path/$tute");
 
  $total_answers = $sdbm{"$question-tried"};
  #$a = "<BR> Student answers are given below. Change the marking credit as you wish.\n <UL>";
  $a = "<BR> Student answers are given below. Change the marking credit as you wish.\n<BR>";
  $i = 0;
  my @options = ('full', 'tq', 'half', 'q', 'none');
  foreach my $option (@options) {
    $a .= "----<BR>\n";
    foreach my $key (keys %qanswerdb) {
      if ($option eq $qanswerdb{$key}) {
        if ($total_answers > 0)  {
          $percent = (10000 * $percentdb{$key} / $total_answers) % 10100;
          }
        else {
          $percent = 0;
          }
        $percent = substr($percent,0,-2) . "." . substr($percent,-2,2);
        #$a .= '<li>';
        # clean up old ones!!!!
        $query->delete("response$i");
        $query->delete("hresponse$i");
        $a .= $query->radio_group(-name=>"response$i",
                                    -values=>['full', 'tq', 'half', 'q', 'none'],
                                    -default=>$qanswerdb{$key});
        $s .= &hidden("hresponse$i",$key);
        $a .= ' -- ';
        $a .= HTML::Entities::encode($key) . "-- $percent% (" . $percentdb{$key} . ")\n";
        $i += 1;
        $a .= '<br/><br/>';
        }
      }
    }
  &closedb(\%qanswerdb, "$path/qanswer$question");
  &closedb(\%percentdb, "$path/percent$question");
  #$s .= "</UL>\n";
  #$a .= "</UL>\n";
  print '<HR>';
  print $query->startform('POST',"$ROOT/dummy.pl");
  print $qdbm{"$question"};
  print $query->endform;
  print $query->startform('POST',"$ROOT/regrader.pl");
  print &hidden('path',$query->param('path'));
  print &hidden('password',$query->param('password'));
  print &hidden('tute','allstats');
  print &hidden('question_list',join(",",($question,@question_list)));
  print $a;
  print $s;
  print $query->submit('action_next', 'Next');
  print $query->submit('action_next_regrade', 'Regrade and goto Next');
  print $query->submit('action_regrade', 'Regrade');
  print $query->endform;
  print '<HR>';
  }

print $query->end_html;

# Test the entry password, if it fails disallow entry to the
# survey and print an appropriate message
sub entry_disallowed {
  if ($query->param('password') eq $directionsdb{'stats-password'}) {return 0;}
  print "Sorry, stats are inactive.";
  return 1;
}

sub hidden {
  my ($name, $value) = @_;
  $query->param($name, $value);
  return $query->hidden($name, $value);
}
