#!/usr/bin/perl -I/home/cdyreson/public_html/cgi-bin/perl/pm
 
# ****************************************************************
# reviewer is a Perl program and CGI-bin script that reviews quiz 
# questions as generated by QuizMaker.  For more info surf to
#       http://www.cs.jcu.edu.au/~curtis/software.html
# You are welcome to send bug reports, fixes, comments, questions or 
# suggestions to Curtis Dyreson at curtis@cs.jcu.edu.au, but as I hope
# to have a real life someday I can't promise a swift reply.
#
# Copyright (c) 1996. All rights reserved.  This software is covered
# under the general license and lack of warranty as stated in the 
# installation kit. WARNING! DANGER WILL ROBINSON! USE AT YOUR OWN RISK!
 
# Persistent hash 
use MyTextDB;
# Lincoln Stein's Fantabulous CGI package
use CGI;

$query = new CGI;
$ROOT = 'http://www.cs.usu.edu/cgi-bin/cgiwrap/~cdyreson/perl/QuizMaker';

#my ($junk, $rest) = split('/', $query->param('path'));
#$path = "C:\\Inetpub\\wwwroot\\Cdyreson\\prweb\\quiz\\$rest";
#$path = $query->param('path');
my ($path) = $query->param('path');
$path = '/home/cdyreson/prweb/QuizMaker' . '/' . $path;
$us = $query->param('userid');
print $query->header;

# Make a security check
die $query->end_html unless &referer_check();
 
#open databases
$us = $query->param('userid');
&openReadOnlydb(\%directionsdb, "$path/directionsdb");
if (defined($directionsdb{'class'})) {
  $ROOT .= '/' . $directionsdb{'class'};
  }
&opendb(\%sadb, "$path/sadb.$us");
&openReadOnlydb(\%qdb, "$path/questiondb");

if (defined($query->param('answer'))) {
  if ($query->param('answer')) {
    $us = $query->param('userid');
    $qu = $query->param('question');
    @ans = $query->param('answer');
    $sadb{"$qu"} = join("\f", @ans);
    }
  }

@question_list = split("\e",$query->param('remaining_questions'));
@answered_list = split("\e",$query->param('answered_questions'));
@review_list = split("\e",$query->param('still_to_review'));
$question = shift(@review_list);
($sec, $ques) = split('.',$question);

# Check to see if there are any more questions, if not then show the
# return to test button
if ($question) {
# Start the form for the next cycle of reviewer
  print $query->start_html("Review Question $sec",'cdyreson@eecs.wsu.edu.au');
  print $directionsdb{'html-base'} . "\n";
  print $query->startform('POST',"$ROOT/reviewer.pl");
  print &hidden('question',$question);
  print &hidden('userid',$query->param('userid'));
  print &hidden('path',$query->param('path'));
  print &hidden('total_questions',$query->param('total_questions'));
  print &hidden('remaining_questions',join("\e",@question_list));
  print &hidden('answered_questions',join("\e",@answered_list));
  print &hidden('still_to_review',join("\e",@review_list));

  # retrieve answer and print it out
  $us = $query->param('userid');
  @studentanswers = split("\f",$sadb{"$question"});
  print '<P> <h2> Your answer is: ' . join(",",@studentanswers) . '</h2>';
  print 'If you are happy with this answer, click here ';
  print $query->submit("action", "Review Next Question");
  print "<BR>";
  print "To change your answer, simply choose a new answer from below";
  print "<BR> <BR>";
  print $query->endform;


  print $query->startform('POST',"$ROOT/reviewer.pl");
  print &hidden('question',$question);
  print &hidden('userid',$query->param('userid'));
  print &hidden('path',$query->param('path'));
  print &hidden('total_questions',$query->param('total_questions'));
  print &hidden('remaining_questions',join("\e",@question_list));
  print &hidden('answered_questions',join("\e",@answered_list));
  print &hidden('still_to_review',join("\e",($question,@review_list)));

  # Question
  print $qdb{$question};
  print $query->endform;
} # this is the end for the if ($question above)

# Show the return to test button
print $query->startform('POST',"$ROOT/marker.pl");
print &hidden('question',$question);
print &hidden('userid',$query->param('userid'));
print &hidden('path',$query->param('path'));
print &hidden('total_questions',$query->param('total_questions'));
print &hidden('remaining_questions',join("\e",@question_list));
print &hidden('answered_questions',join("\e",@answered_list));
print &hidden('still_to_review',join("\e",@review_list));
print '<P> <HR> Finished reviewing.';
print $query->submit("action", "Return to Quiz");
print $query->endform;

print $query->end_html;

&closedb(\%sadb, "$path/sadb.$us");

sub hidden {
  my ($name, $value) = @_;
  $query->param($name, $value);
  return $query->hidden($name, $value);
}

# Test the HTTP_REFERER variable, if it fails disallow entry to the
# survey and print an appropriate message
sub referer_check{
  my ($referer) = $ENV{'HTTP_REFERER'};
 
  if ($referer =~ /^$ROOT/) { return 1; }
  print "Sorry, access attempted from an untrustworthy source.";
  return 0;
}
