#!/usr/bin/perl -I/home/cdyreson/public_html/cgi-bin/perl/pm
 
# ****************************************************************
# starter is a Perl program and CGI-bin script that does the quiz
# entry stuff to a quiz generated by QuizMaker.  For more info surf to
#       http://www.cs.jcu.edu.au/~curtis/software.html
# You are welcome to send bug reports, fixes, comments, questions or
# suggestions to Curtis Dyreson at curtis@cs.jcu.edu.au, but as I hope
# to have a real life someday I can't promise a swift reply.
#
# Copyright (c) 1996. All rights reserved.  This software is covered
# under the general license and lack of warranty as stated in the
# installation kit. WARNING! DANGER WILL ROBINSON! USE AT YOUR OWN RISK!
 
# persistent associative hash
use MyTextDB;
 
# Lincoln Stein's Fantabulous CGI package
use CGI;

$query = new CGI;
$ROOT = 'http://www.cs.usu.edu/cgi-bin/cgiwrap/~cdyreson/perl/QuizMaker';

# Build the header
print $query->header; 
print $query->start_html('Entry to Quiz','Curtis.Dyreson at usu.edu');

# Open databases
#$path = $query->param('path');
my ($path) = $query->param('path');
$path = '/home/cdyreson/prweb/QuizMaker' . '/' . $path;

&openReadOnlydb(\%directionsdb, "$path/directionsdb");
if (defined($directionsdb{'class'})) {
  $ROOT .= '/' . $directionsdb{'class'};
  }
# if condition for fake quiz
&openReadOnlydb(\%randomdb, "$path/randomdb");

#it is a horrible hack but the security check will set the login 
$login = "Noone we know!"; 
# Make a security check
if (&entry_disallowed()) {
  print $query->end_html;
  exit();
  }

# security passed, continue
if (-e "$path/passworddb") {
  &openReadOnlydb(\%classdb, "$path/classdb");
  $person = $classdb{$login};
  }
else {
  # is a fake quiz
  $person = $login;
  }

if (-e "$path/sadb.$login") {
  #previously opened
  &opendb(\%sanswerdb, "$path/sadb.$login");
  $seed = $sanswerdb{"seed"};
  }
else {
  # open new answer db
  &opendb(\%sanswerdb, "$path/sadb.$login");
  $seed = time;
  $sanswerdb{"seed"} = $seed;
  }
 
srand($seed);
@question_list = ();
@answered_list = ();
@keys = sort keys %randomdb;
$questions_max = scalar(@keys);
for ($i=1; $i <= $questions_max; $i++) {
  $j = int(rand($randomdb{$i})) + 1;
  $question = "$i.$j";
  if (defined($sanswerdb{$question})) {push(@answered_list,$question);}
  else {push(@question_list,$question);}
  }

print $query->startform('POST',"$ROOT/marker.pl");
print $query->hidden('userid',$login);
print $query->hidden('path',$query->param('path'));
print $query->hidden('remaining_questions',join("\e",@question_list));
print $query->hidden('answered_questions',join("\e",@answered_list));

print <<DIRECTIONS;
Hello $person!
<P>
Take the quiz at your own pace.  When you are finished (or whenever you 
like), review your answers by choosing the appropriate button.  
<BR>
DIRECTIONS

print $query->submit("action", "Start Quiz");

print $query->endform;
print $query->end_html;

&closedb(\%sanswerdb, "$path/sadb.$login");

# Test the time and entry password, if either fails disallow entry to the
# quiz and print an appropriate message
sub entry_disallowed {
  local (@lines, $date, $time, $entry, $submit, $line, $ehour, $eday, 
         $emonth, $month, $second, $minute, $hour, $day, $month, $year,
         $password);

  #for the fake quiz just go ahead
  if (!(-e "$path/passworddb")) {
    $login = $query->param('password');
    return 0;
    }

  #figure out the entry codes and times 
  ($second, $minute, $hour, $day, $month, $year) = localtime(time);
  $month++;
  $silly = "\n";
  @lines = split($silly, $directionsdb{'test-entry'});
  foreach $line (@lines) {
    ($date, $tme, $entry, $submit) = split(/\s+/, $line);
    ($emonth, $eday) = split('/', $date);
    ($ehour, $thour) = split('.', $tme);
  
    #if (($ehour <= $hour) &&
    #    ($hour <= $thour) &&
    #    ($eday == $day) &&
    #    ($emonth == $month)) {
    &opendb(\%passworddb, "$path/passworddb");
    if (1) {
      $password = $query->param('password');
      if (defined $passworddb{$password}) {
         $login = $passworddb{$password};

         &opendb(\%spassworddb, "$path/pass.$login");
         if (defined $spassworddb{$password}) {
           # test is activated
           delete $spassworddb{$password};
           &closedb(\%spassworddb, "$path/pass.$login");
           return 0;
           }
         else {
           #used password
           print 'Please obtain a new password from your tutor and try again.';
           return 1;
           }
         }
      else {
        #bad password
        print 'Sorry, perhaps you typed your password incorrectly?';
        return 1;
        }

      }
    }
  print 'Sorry, the quiz is inactive.';
  return 1;
}
