#!/usr/local/bin/perl -IC:\Inetpub\wwwroot\CDyreson\cgi-bin\perl\pm -IC:\Inetpub\wwwroot\CDyreson\cgi-bin\perl\quiz
 
# ****************************************************************
# poster is a Perl program and CGI-bin script that turnins in a 
# quiz as generated by QuizMaker.  For more info surf to
#       http://www.cs.jcu.edu.au/~curtis/software.html
# You are welcome to send bug reports, fixes, comments, questions or 
# suggestions to Curtis Dyreson at curtis@cs.jcu.edu.au, but as I hope
# to have a real life someday I can't promise a swift reply.
#
# Copyright (c) 1996. All rights reserved.  This software is covered
# under the general license and lack of warranty as stated in the 
# installation kit. WARNING! DANGER WILL ROBINSON! USE AT YOUR OWN RISK!
 
# persistent associative hash
use MyTextDB;

# Lincoln Stein's Fantabulous CGI package
use CGI;

$query = new CGI;
print $query->header;
print $query->start_html('Quiz Finished','cdyreson@bond.edu.au');

#open databases
$us = $query->param('userid');
my ($junk, $rest) = split('/', $query->param('path'));
$path = "C:\\Inetpub\\wwwroot\\Cdyreson\\prweb\\quiz\\$rest";
#$path = $query->param("path");

#open databases
&opendb(\%directionsdb, "$path\\directionsdb");
&opendb(\%randomdb, "$path\\randomdb");
&opendb(\%rvclassdb, "$path\\rvclassdb");
&opendb(\%classdb, "$path\\classdb");
&opendb(\%sanswerdb, "$path\\sadb.$us");

# Don't worry be happy

# If we find an answer, then answer it
$message = 'Your name is ' . $classdb{$us} . "\n";
$message .= 'Your email address is ' . $us . "\n\n";
foreach $key (sort keys %sanswerdb) {
  next if ($key eq "seed");
  ($sec) = split(":", $key);
  $message .= $sec . " " . $sanswerdb{$key} . "\n";
  }
$message =~ s/\f/,/g;

if (!defined $directionsdb{'email'}) { die "no email address" };
$email = $directionsdb{'email'};
$class = $directionsdb{'class'};

# for fake quiz
if (-e "$path\\passworddb") {
  open(MAIL,"|/usr/bin/mailx -s \"####QUIZ $class\" $email") || die "cannot open mailx! contact your tutor";
  print MAIL $message;
  close(MAIL);
}

$temp = $classdb{"$us"};
delete $rvclassdb{$temp};
delete $classdb{$us};
$message = "This message is automatically generated.  Please do not reply to it.\n\n" . $message;

# for fake quiz
if (-e "$path\\passworddb") {
  open(MAIL,"|/usr/bin/mailx -s \"A Copy of Your Quiz Answers\" $us\@jcu.edu.au ") || die "cannot open mailx! contact your tutor";
  print MAIL $message;
  close(MAIL);
  }

print '<P>';
print '<H1> Congratulations ' . $query->param("username") . ', you have finished the Quiz! </H1>';
print $directionsdb{'return-to-where'};

print $query->end_html;
