code: Cube.class MessageLayout.class MessageHandler.class 

Cube.class: 
	javac Cube.java

MessageLayout.class:
	javac MessageLayout.java

MessageHandler.class:
	javac MessageHandler.java

clean: 
	rm -f *.class
