JAVA_FLAGS=-classpath ../..
code: Tuple.class Table.class Database.class Id.class IdSet.class IdList.class StringCol.class Dbm.class IdEnumeration.class IntegerCol.class Convert.class

Dbm.class: Dbm.java
	javac $(JAVA_FLAGS) Dbm.java

IdList.class: IdList.java
	javac $(JAVA_FLAGS) IdList.java

Table.class: Table.java
	javac $(JAVA_FLAGS) Table.java

IntegerCol.class: IntegerCol.java
	javac $(JAVA_FLAGS) IntegerCol.java

StringCol.class: StringCol.java
	javac $(JAVA_FLAGS) StringCol.java

IdSet.class: IdSet.java
	javac $(JAVA_FLAGS) IdSet.java

IdEnumeration.class: IdEnumeration.java
	javac $(JAVA_FLAGS) IdEnumeration.java

Id.class: Id.java
	javac $(JAVA_FLAGS) Id.java

Tuple.class: Tuple.java
	javac $(JAVA_FLAGS) Tuple.java

Database.class: Database.java
	javac $(JAVA_FLAGS) Database.java

clean: 
	rm -f *.class
